### ISSUE TITLE
App crashes when opening specific link

### ISSUE THREAD

**Issue by shrugal** [dessalines/jerboa#1020]
**Jerboa Version**
Tried on 0.0.38 and 0.0.39

**Android version + phone**
Pixel 4, Android 13

**Describe the bug**
The following post and others with the same link crash the app every time when opening the link: https://lemmy.ml/post/1956845

Other links seem to work just fine.

**To Reproduce**

1. Just tap on the link in the post

**In the case of a crash**
I'm on my phone right now, will add the logs later.

**Comment by MV-GH** [comment]
Con confirm



<details> <summary>These are the logs </summary>
FATAL EXCEPTION: main
                                                                                                    Process: com.jerboa, PID: 19973
                                                                                                    java.lang.IllegalArgumentException: Cannot navigate to NavDeepLinkRequest{ uri=android-app://androidx.navigation/www.suse.com/c/at-suse-we-make-choice-happen }. Navigation graph has not been set for NavController androidx.navigation.NavHostController@e92ddb1.
                                                                                                    	at androidx.navigation.NavController.navigate$default(Unknown Source:154)
                                                                                                    	at com.jerboa.UtilsKt.openLink(Unknown Source:563)
                                                                                                    	at com.jerboa.ui.components.post.PostListingKt$ThumbnailTile$1$postLinkPicMod$1.invoke(Unknown Source:29)
                                                                                                    	at androidx.compose.material3.AppBarKt$settleAppBar$3.invoke(SourceFile:99)
                                                                                                    	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(Unknown Source:133)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
                                                                                                    	at arrow.core.Ior.resume(Unknown Source:80)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(Unknown Source:137)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(Unknown Source:44)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(Unknown Source:16)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(Unknown Source:50)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(Unknown Source:30)
                                                                                                    	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Unknown Source:4)
                                                                                                    	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Unknown Source:4)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:180)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:159)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:159)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:159)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:159)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:159)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:159)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:159)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Unknown Source:159)
                                                                                                    	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(Unknown Source:25)
                                                                                                    	at androidx.compose.ui.platform.WeakCache.dispatchChanges(Unknown Source:26)
                                                                                                    	at androidx.emoji2.text.EmojiProcessor.process-BIzXfog(Unknown Source:184)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(Unknown Source:78)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(Unknown Source:223)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(Unknown Source:87)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:501)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1875)
                                                                                                    	at android.app.Activity.dispatchTouchEvent(Activity.java:4225)
2023-07-12 13:21:12.466 19973-19973 AndroidRuntime          com.jerboa                           E  	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchTouchEvent$androidx$appcompat$view$WindowCallbackWrapper(Unknown Source:2)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchTouchEvent(Unknown Source:0)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:459)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:14655)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6278)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6065)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5520)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5577)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5543)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5695)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5551)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5752)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5524)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5577)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5543)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5551)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5524)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8404)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8355)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8315)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8540)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:241)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8061)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@f15e204, androidx.compose.runtime.BroadcastFrameClock@a46a3ed, StandaloneCoroutine{Cancelling}@c543222, AndroidUiDispatcher@f6be4b3]
2023-07-12 13:21:12.518 19973-19973 Process                 com.jerboa                           I  Sending signal. PID: 19973 SIG: 9
</details>

**Comment by MV-GH** [comment]
The url `https://www.suse.com/c/at-suse-we-make-choice-happen/` gets incorrectly parsed as a community url
![image](https://github.com/dessalines/jerboa/assets/67873169/3ccb6b4d-5e87-45a1-8bac-2b60674cc7e3)

**Comment by MV-GH** [comment]
```kt
fun looksLikeCommunityUrl(url: String): Pair<String, String>? {
    val pattern = Regex("^https?://([^/]+)/c/([^/&?]+)")
    val match = pattern.find(url)
    if (match != null) {
        val (host, community) = match.destructured
        return Pair(host, community)
    }
    return null
}
```

Currently it assumes that if a link contains a `/c/` path segment that it is a community URL. Which is not a good approach. 
What we can do is only allow community links where the host is in the DEFAULT_LEMMY_INSTANCES but that does mean it won't work for lemmy instances that aren't in the list. Or pass a flag in openLink that for some it should never check those when clicking on a link, and only enable that flag for the urlspans that use them.

What are you thoughts on this @twizmwazin ?

**Comment by twizmwazin** [comment]
I think if we can check if a community/user link is valid before opening the link, that would be the best approach. If this check is slow we could also cache results on a per-domain level, pre-seeding that cache with known instances.

**Comment by MV-GH** [comment]
Well the thing is, we would have to check every link in the posts. That's a lot of domains that needs to be checked. And each check would have to be a minimum of a network request to /v3/site , to check version and if its a lemmy instance. At this point i am leaning more towards allowing only the formats `!instance` to redirect to url (without check and thus allowing it to redirect to communities/instances that don't exist) and others only if it is in the lemmy instance list. Either way that is gonna be in a separate pr. Atm trying to fix the second issue first.

**Comment by twizmwazin** [comment]
We don't need to check every link in a post, only links that the user clicks on, when they click on them. Additionally, we can cache known domains to avoid future checks. It would be one request to `/v3/site` the first time a user clicks a link to a domain, only if the link looks like a community/user url, and big instances would be pre-cached.
