### ISSUE TITLE
FATAL EXCEPTION

### ISSUE THREAD

**Issue by Rustmilian** [dessalines/jerboa#1067]
### Jerboa Version

0.0.40

### Android Version + Phone

Android 13

### Describe The Bug

Crash FATAL EXCEPTION: main
See log.

### To Reproduce

1. Go to search
2. Open instances and close them until crash.

### In the case of a crash or when relevant include the logs

```java
FATAL EXCEPTION: main
Process: com.jerboa, PID: 8231
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(Unknown Source:21)
	at com.google.gson.stream.JsonReader.checkLenient(Unknown Source:7)
	at com.google.gson.stream.JsonReader.doPeek(Unknown Source:634)
	at com.google.gson.stream.JsonReader.peek$enumunboxing$(Unknown Source:4)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source:0)
	at androidx.compose.ui.platform.WeakCache.convert(Unknown Source:44)
	at retrofit2.OkHttpCall.parseResponse(Unknown Source:58)
	at retrofit2.OkHttpCall$1.onResponse(Unknown Source:4)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(Unknown Source:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ce2421d, Dispatchers.Main.immediate] 
```

**Comment by MV-GH** [comment]
Can we get full logs?

What action did you do to get this. It seems more likely the BE did an oopsie.
 But can't be too sure without seeing the request.

**Comment by MV-GH** [comment]
Will close, you can reopen with more info. But I don't understand the repro steps. And stacktrace doesn't show anything from which requests caused this or the body that was attempted to parse.
