### ISSUE TITLE
Crash on clicking a read more replies in a post

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1109]
### Jerboa Version

0.0.41

### Android Version + Phone

Android 8 pixel in emulator

### Describe The Bug

I was clicking on a read more replies and then it crashed with `java.lang.IllegalArgumentException: Key "2090453" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.` See logs for full logs

### To Reproduce

go to this post https://lemmy.ml/post/2568562
-> go to the open more replies
-> click it

https://github.com/dessalines/jerboa/assets/67873169/b65562ec-9048-40de-98a2-aa4d8e3e14f1

### In the case of a crash or when relevant include the logs

<details><summary>LOGS</summary>
<-- END HTTP (2701-byte body)
--> GET https://lemmy.ml/api/v3/comment/list?max_depth=6&parent_id=2090453&type_=All
--> END GET
<-- 200 https://lemmy.ml/api/v3/comment/list?max_depth=6&parent_id=2090453&type_=All (46ms, unknown-length body)
server: nginx
date: Sat, 29 Jul 2023 04:50:02 GMT
content-type: application/json
access-control-expose-headers: content-type, content-encoding, vary
vary: accept-encoding, Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
referrer-policy: same-origin
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
{"comments":[{"comment":{"id":2090686,"creator_id":838903,"post_id":2568562,"content":"It's not a criticism. It just wasn't to my taste.","removed":false,"published":"2023-07-29T04:45:28.575867","deleted":false,"ap_id":"https:\/\/lemmy.ca\/comment\/1699010","local":false,"path":"0.2088635.2088937.2089235.2089291.2089718.2090453.2090686","distinguished":false,"language_id":37},"creator":{"id":838903,"name":"floofloof","banned":false,"published":"2023-06-16T20:57:24.782101","actor_id":"https:\/\/lemmy.ca\/u\/floofloof","local":false,"deleted":false,"admin":false,"bot_account":false,"instance_id":210},"post":{"id":2568562,"name":"Developer of Reddit is Fun just released an app for Tildes.","url":"https:\/\/tildes.net\/~tildes\/18s2\/three_cheers_for_tildes_android_version_is_open_for_alpha_testing_on_the_google_play_store","creator_id":625710,"community_id":16,"removed":false,"locked":false,"published":"2023-07-29T02:45:14.578842","deleted":false,"nsfw":false,"embed_title":"Three Cheers for Tildes (Android version) is open for alpha testing on the Google Play Store - ~tildes","embed_description":"69 comments in the discussion of this post on Tildes","thumbnail_url":"https:\/\/lemmy.ml\/pictrs\/image\/9a650d23-04bb-4c5c-ad3f-8032c6c703c2.png","ap_id":"https:\/\/lemmy.ml\/post\/2568562","local":true,"language_id":0,"featured_community":false,"featured_local":false},"community":{"id":16,"name":"technology","title":"Technology","description":"This is the official technology community of Lemmy.ml for all news related to creation and use of technology, and to facilitate civil, meaningful discussion around it.\n\n---\n\nRules:\n\n1: All Lemmy rules apply\n\n2: Do not post low effort posts\n\n3: NEVER post naziped*gore stuff\n\n4: Always post article URLs or their archived version URLs as sources, NOT screenshots. Help the blind users.","removed":false,"published":"2019-04-25T21:58:01.788609","updated":"2023-06-16T08:43:35.744685","deleted":false,"nsfw":false,"actor_id":"https:\/\/lemmy.ml\/c\/technology","local":true,"icon":"https:\/\/lemmy.ml\/pictrs\/image\/2QNz7bkA1V.png","hidden":false,"posting_restricted_to_mods":false,"instance_id":394},"counts":{"id":1844199,"comment_id":2090686,"score":1,"upvotes":1,"downvotes":0,"published":"2023-07-29T04:45:28.575867","child_count":0,"hot_rank":1728},"creator_banned_from_community":false,"subscribed":"NotSubscribed","saved":false,"creator_blocked":false},{"comment":{"id":2090453,"creator_id":1145297,"post_id":2568562,"content":"It’s literally the tech bro news site, though, by design. This criticism is ridiculous. YCombinator is the organization that funds so many Silicon Valley tech dreams.","removed":false,"published":"2023-07-29T04:31:10.587558","deleted":false,"ap_id":"https:\/\/lemmy.world\/comment\/1840944","local":false,"path":"0.2088635.2088937.2089235.2089291.2089718.2090453","distinguished":false,"language_id":0},"creator":{"id":1145297,"name":"pbbananaman","banned":false,"published":"2023-06-28T15:35:32.621615","actor_id":"https:\/\/lemmy.world\/u\/pbbananaman","local":false,"deleted":false,"admin":false,"bot_account":false,"instance_id":136816},"post":{"id":2568562,"name":"Developer of Reddit is Fun just released an app for Tildes.","url":"https:\/\/tildes.net\/~tildes\/18s2\/three_cheers_for_tildes_android_version_is_open_for_alpha_testing_on_the_google_play_store","creator_id":625710,"community_id":16,"removed":false,"locked":false,"published":"2023-07-29T02:45:14.578842","deleted":false,"nsfw":false,"embed_title":"Three Cheers for Tildes (Android version) is open for alpha testing on the Google Play Store - ~tildes","embed_description":"69 comments in the discussion of this post on Tildes","thumbnail_url":"https:\/\/lemmy.ml\/pictrs\/image\/9a650d23-04bb-4c5c-ad3f-8032c6c703c2.png","ap_id":"https:\/\/lemmy.ml\/post\/2568562","local":true,"language_id":0,"featured_community":false,"featured_local":false},"community":{"id":16,"name":"technology","title":"Technology","description":
"This is the official technology community of Lemmy.ml for all news related to creation and use of technology, and to facilitate civil, meaningful discussion around it.\n\n---\n\nRules:\n\n1: All Lemmy rules apply\n\n2: Do not post low effort posts\n\n3: NEVER post naziped*gore stuff\n\n4: Always post article URLs or their archived version URLs as sources, NOT screenshots. Help the blind users.","removed":false,"published":"2019-04-25T21:58:01.788609","updated":"2023-06-16T08:43:35.744685","deleted":false,"nsfw":false,"actor_id":"https:\/\/lemmy.ml\/c\/technology","local":true,"icon":"https:\/\/lemmy.ml\/pictrs\/image\/2QNz7bkA1V.png","hidden":false,"posting_restricted_to_mods":false,"instance_id":394},"counts":{"id":1843982,"comment_id":2090453,"score":1,"upvotes":1,"downvotes":0,"published":"2023-07-29T04:31:10.587558","child_count":1,"hot_rank":1415},"creator_banned_from_community":false,"subscribed":"NotSubscribed","saved":false,"creator_blocked":false}]}
<-- END HTTP (4913-byte body)
Shutting down VM
FATAL EXCEPTION: main
Process: com.jerboa.debug, PID: 688
java.lang.IllegalArgumentException: Key "2090453" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:660)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:1014)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:121)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure(LazyListMeasuredItemProvider.kt:48)
	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-CD5nmq0(LazyListMeasure.kt:159)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke-0kLqBqw(LazyList.kt:306)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:184)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke-0kLqBqw(LazyLayout.kt:87)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(LazyLayout.kt:80)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:866)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:646)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(Padding.kt:397)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1499)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1495)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:462)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1495)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:35)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:560)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1134)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(LayoutNode.kt:1125)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:323)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:458)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:39)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:344)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:879)
	at androidx.compose.ui.node.Owner.measureAndLayout$default(Owner.kt:223)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1127)
	at android.view.View.draw(View.java:19126)
	at android.view.View.updateDisplayListIfDirty(View.java:18073)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
	at android.view.View.updateDisplayListIfDirty(View.java:18032)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
	at android.view.View.updateDisplayListIfDirty(View.java:18032)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
	at android.view.View.updateDisplayListIfDirty(View.java:18032)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
	at android.view.View.updateDisplayListIfDirty(View.java:18032)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
	at android.view.View.updateDisplayListIfDirty(View.java:18032)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
	at android.view.View.updateDisplayListIfDirty(View.java:18032)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2980)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2794)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2347)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

</details>

**Comment by MV-GH** [comment]
Did some digging, this is what returns the comments https://lemmy.ml/api/v3/comment/list?max_depth=6&post_id=2568562&sort=Hot&type_=All

And this is what returns the more replies https://lemmy.ml/api/v3/comment/list?max_depth=6&parent_id=2090453&type_=All

As we can see the parent is 2090453 but this request returns two comments the actual reply AND the parent again

**Comment by dessalines** [comment]
Search for the content field there, it's actually 2 separate comments, which includes the parent.

**Comment by MV-GH** [comment]
Yeah i figured that out afterwards but the order did change. Previously it would always put the parent in the first position.

**Comment by dessalines** [comment]
Gotcha... that probably got changed as I fixed the `hot` comment sort in the back end. That means we need to update our tree building function logic to be more resilient and account for mis-ordering.
