### ISSUE TITLE
Does not load images that use HTTP protocol

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1192]
### Jerboa Version

0.0.44

### Android Version + Phone

Android 11

### Describe The Bug

images that use the HTTP scheme do not load, at least that is what I assume from the error message

Solutions for this https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

But I am not sure if enabling clearText is wanted, maybe if possible only override it for images?

### To Reproduce

go to this post https://lemmy.ml/api/v3/post?id=3516120

it this image http://0.vern.cc/fn.jpg

### In the case of a crash or when relevant include the logs

<details> <summary> stacktrace </summary>

failed saving media
java.net.UnknownServiceException: CLEARTEXT communication to 0.vern.cc not permitted by network security policy
	at okhttp3.internal.connection.RealRoutePlanner.planConnectToRoute$okhttp(Unknown Source:50)
	at okhttp3.internal.connection.RealRoutePlanner.plan(Unknown Source:763)
	at okhttp3.internal.connection.FastFallbackExchangeFinder.launchTcpConnect(Unknown Source:9)
	at okhttp3.internal.connection.FastFallbackExchangeFinder.find(Unknown Source:67)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown Source:27)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:138)
	at okhttp3.internal.cache.CacheInterceptor.intercept(Unknown Source:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:138)
	at okhttp3.internal.http.BridgeInterceptor.intercept(Unknown Source:152)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:138)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown Source:170)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:138)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(Unknown Source:95)
	at okhttp3.internal.connection.RealCall.execute(Unknown Source:41)
	at com.jerboa.UtilsKt.getInputStream(Unknown Source:89)
	at com.jerboa.feat.UserActionsKt$saveMedia$2.invokeSuspend(Unknown Source:9)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at androidx.core.app.ActivityRecreator$1.run(Unknown Source:15)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
	Suppressed: java.net.UnknownServiceException: CLEARTEXT communication to 0.vern.cc not permitted by network security policy
		at okhttp3.internal.connection.RealRoutePlanner.planConnectToRoute$okhttp(Unknown Source:50)
		at okhttp3.internal.connection.RealRoutePlanner.plan(Unknown Source:152)
		... 19 more

</details>

**Comment by MV-GH** [comment]
I have also noticed but when it turns a instance into a link, ex: `lemmy.one` it also uses the HTTP scheme instead of HTTPS

![image](https://github.com/dessalines/jerboa/assets/67873169/a4d86afb-b401-40d3-9850-94fa2bc1d313)
