### ISSUE TITLE
Weird edge case crash, cant reproduce anymore after submit on reply private message

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1211]
### Jerboa Version

0.0.45

### Android Version + Phone

N/A

### Describe The Bug

sent a message on submit I came back to the inbox, started lagging hard, scrolled down crash.

from the log, I can see it did a request on returning to the inbox , which i am not sure why it did that but either way it should not have crashed. from the requests it requsetd paged 2 and probably merged that with page 1 which somehow much have had message `1191` already

got to inbox activity
got to private message reply activity
got to private message reply activity
Frame time is 0.024011 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
--> POST https://lemmy.world/api/v3/private_message (206-byte body)
Content-Type: application/json; charset=UTF-8
{"auth":"REDACTED","content":"stts v.0.4","recipient_id":1022481}
--> END POST (206-byte body)
got to private message reply activity
requestCursorAnchorInfo on inactive InputConnection
<-- 200 https://lemmy.world/api/v3/private_message (208ms, unknown-length body)
date: Sat, 02 Sep 2023 00:05:06 GMT
content-type: application/json
vary: accept-encoding, Origin, Access-Control-Request-Method, Access-Control-Request-Headers
access-control-expose-headers: content-encoding, vary, content-type
strict-transport-security: max-age=63072000
referrer-policy: same-origin
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=a5PznGxroQWrqgfzsJUnyiJa727jEWPPTxk0jeZRVsq2SE5rNksy0G0lsCojKmv7QbyeDIxjTCy74FaGF6QNerI8qnIVwhYRCc1xtv73ArJ3JSnQiCQ88j9o%2BFmA"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 80017fda1a7a0b52-AMS
{"private_message_view":{"private_message":{"id":18563,"creator_id":1376972,"recipient_id":1022481,"content":"stts v.0.4","deleted":false,"read":false,"published":"2023-09-02T00:05:06.280336","ap_id":"https:\/\/lemmy.world\/private_message\/18563","local":true},"creator":{"id":1376972,"name":"testEmailVerified","banned":false,"published":"2023-07-25T19:52:43.703582","actor_id":"https:\/\/lemmy.world\/u\/testEmailVerified","local":true,"deleted":false,"admin":false,"bot_account":false,"instance_id":1},"recipient":{"id":1022481,"name":"testAccount","banned":false,"published":"2023-07-03T03:39:38.697660","actor_id":"https:\/\/programming.dev\/u\/testAccount","local":false,"deleted":false,"admin":false,"bot_account":false,"instance_id":516}}}
<-- END HTTP (736-byte body)

got to private message reply activity
got to private message reply activity
got to inbox activity
got to inbox activity
requestCursorUpdates is not supported
got to inbox activity
got to inbox activity
got to inbox activity
got to inbox activity
got to inbox activity
requestCursorAnchorInfo on inactive InputConnection
got to inbox activity
--> GET https://lemmy.world/api/v3/private_message/list?page=2&unread_only=false&auth=REDACTED
--> END GET
<-- 200 https://lemmy.world/api/v3/private_message/list?page=2&unread_only=false&auth=REDACTED (181ms, unknown-length body)
date: Sat, 02 Sep 2023 00:05:09 GMT
content-type: application/json
vary: accept-encoding, Origin, Access-Control-Request-Method, Access-Control-Request-Headers
access-control-expose-headers: content-type, vary, content-encoding
strict-transport-security: max-age=63072000
referrer-policy: same-origin
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=SxpatgafIPUDFWDuFk1fR%2FxowcHpuLDGlhUkIEjWiDsVyXqoBdK%2BbdNVCqLrJpD3FM0FRtZWbrVIx6s4LG2CWqwh%2Fo%2FFpd2enceM1B%2B4uWpoz1w%2B1glxunpyIQVn"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 80017feffa360b52-AMS
{"private_messages":[{"private_message":{"id":11911,"creator_id":1376972,"recipient_id":148410,"content":"Did you get this?","deleted":false,"read":true,"published":"2023-07-27T23:06:36.444818","ap_id":"https:\/\/lemmy.world\/private_message\/11911","local":true},"creator":{"id":1376972,"name":"testEmailVerified","banned":false,"published":"2023-07-25T19:52:43.703582","actor_id":"https:\/\/lemmy.world\/u\/testEmailVerified","local":true,"deleted":false,"admin":false,"bot_account":false,"instance_id":1},"recipient":{"id":148410,"name":"testAccount","banned":false,"published":"2023-06-07T17:25:57.885660","actor_id":"https:\/\/lemmy.one\/u\/testAccount","local":false,"banner":"https:\/\/lemmy.one\/pictrs\/image\/5e51c666-18d1-4170-8f52-57d4639cca5b.jpeg","deleted":false,"matrix_user_id":"@mdevatriz:matrix.org","admin":false,"bot_account":false,"instance_id":249}},{"private_message":{"id":11910,"creator_id":1376972,"recipient_id":148410,"content":"Did you get it?","deleted":false,"read":true,"published":"2023-07-27T23:00:24.939717","ap_id":"https:\/\/lemmy.world\/private_message\/11910","local":true},"creator":{"id":1376972,"name":"testEmailVerified","banned":false,"published":"2023-07-25T19:52:43.703582","actor_id":"https:\/\/lemmy.world\/u\/testEmailVerified","local":true,"deleted":false,"admin":false,"bot_account":false,"instance_id":1},"recipient":{"id":148410,"name":"testAccount","banned":false,"published":"2023-06-07T17:25:57.885660","actor_id":"https:\/\/lemmy.one\/u\/testAccount","local":false,"banner":"https:\/\/lemmy.one\/pictrs\/image\/5e51c666-18d1-4170-8f52-57d4639cca5b.jpeg","deleted":false,"matrix_user_id":"@mdevatriz:matrix.org","admin":false,"bot_account":false,"instance_id":249}}]}
<-- END HTTP (1690-byte body)

### To Reproduce

n/a

### In the case of a crash or when relevant include the logs

FATAL EXCEPTION: main
Process: com.jerboa.debug, PID: 28934
java.lang.IllegalArgumentException: Key "11911" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:660)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:1014)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:121)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure(LazyListMeasuredItemProvider.kt:48)
	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-CD5nmq0(LazyListMeasure.kt:159)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke-0kLqBqw(LazyList.kt:306)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:184)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke-0kLqBqw(LazyLayout.kt:87)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(LazyLayout.kt:80)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:866)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:646)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(Size.kt:698)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1499)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1495)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1495)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:35)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:560)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1140)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:321)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout-0kLqBqw(MeasureAndLayoutDelegate.kt:389)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout-0kLqBqw(AndroidComposeView.android.kt:890)
	at androidx.compose.ui.node.LayoutNode.forceRemeasure(LayoutNode.kt:1214)
	at androidx.compose.foundation.lazy.LazyListState.onScroll$foundation_release(LazyListState.kt:301)
	at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:162)
	at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:162)
	at androidx.compose.foundation.gestures.DefaultScrollableState$scrollScope$1.scrollBy(ScrollableState.kt:166)
	at androidx.compose.foundation.gestures.ScrollingLogic$dispatchScroll$performScroll$1.invoke-MK-Hz9U(Scrollable.kt:425)
	at androidx.compose.foundation.gestures.ScrollingLogic$dispatchScroll$performScroll$1.invoke(Scrollable.kt:417)
	at androidx.compose.foundation.AndroidEdgeEffectOverscrollEffect.applyToScroll-Rhakbz0(AndroidOverscroll.kt:180)
	at androidx.compose.foundation.gestures.ScrollingLogic.dispatchScroll-3eAAhYA(Scrollable.kt:438)
	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$outerScopeScroll$1.invoke-MK-Hz9U(Scrollable.kt:490)
	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$outerScopeScroll$1.invoke(Scrollable.kt:489)
	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$scope$1.scrollBy(Scrollable.kt:494)
	at androidx.compose.foundation.gestures.DefaultFlingBehavior$performFling$2$1.invoke(Scrollable.kt:605)
	at androidx.compose.foundation.gestures.DefaultFlingBehavior$performFling$2$1.invoke(Scrollable.kt:603)
	at androidx.compose.animation.core.SuspendAnimationKt.doAnimationFrame(SuspendAnimation.kt:361)
	at androidx.compose.animation.core.SuspendAnimationKt.doAnimationFrameWithScale(SuspendAnimation.kt:339)
	at androidx.compose.animation.core.SuspendAnimationKt.access$doAnimationFrameWithScale(SuspendAnimation.kt:1)
	at androidx.compose.animation.core.SuspendAnimationKt$animate$9.invoke(SuspendAnimation.kt:279)
	at androidx.compose.animation.core.SuspendAnimationKt$animate$9.invoke(SuspendAnimation.kt:278)
	at androidx.compose.animation.core.SuspendAnimationKt$callWithFrameNanos$2.invoke(SuspendAnimation.kt:304)
	at androidx.compose.animation.core.SuspendAnimationKt$callWithFrameNanos$2.invoke(SuspendAnimation.kt:303)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:544)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1074)
	at android.view.Choreographer.doCallbacks(Choreographer.java:897)
	at android.view.Choreographer.doFrame(Choreographer.java:822)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@94367bf, androidx.compose.runtime.BroadcastFrameClock@8098e8c, StandaloneCoroutine{Cancelling}@1c889d5, AndroidUiDispatcher@c1fc5ea]

**Comment by MV-GH** [comment]
I think i figured it out, the request is because it hit the end of the list so it loaded  the next batch of messages, because of the new message, the whole list is moved up and a duplicate ends up in the second page. Like we do with posts we need to filter duplicates out
