### ISSUE TITLE
Crash when pressing "create post" button in a certain community

### ISSUE THREAD

**Issue by firefoxlover** [dessalines/jerboa#1292]
### Jerboa Version

0.0.51

### Android Version + Phone

GrapheneOS Android 14, Pixel4a

### Describe The Bug

I am on feddit.de and try to create a post in dach@feddit.de

When pressing the plus button the app crashes, reproducible

### To Reproduce

1

### In the case of a crash or when relevant include the logs

```
type: crash
osVersion: google/sunfish/sunfish:13/TQ3A.230805.001.S1/2023110900:user/release-keys
package: com.jerboa:51
process: com.jerboa
processUptime: 7629 + 405 ms
installer: org.fdroid.basic

java.lang.IllegalArgumentException: MutableState containing Community(id=48758, name=dach, title=DACH - Deutschsprachige Community für Deutschland, Österreich, Schweiz, description=Das Sammelbecken auf **feddit** für alle Deutschsprechenden aus Deutschland, Österreich, Schweiz, Liechtenstein, Luxemburg und die zwei Belgier. Außerdem natürlich alle anderen deutschprechenden Länderteile der Welt.

Für länderspezifische Themen könnt ihr euch in folgenden Communities austauschen:

- [!deutschland@feddit.de](https://feddit.de/c/deutschland) 
- [!austria@feddit.de](https://feddit.de/c/austria) 
- [!schweiz@feddit.de](https://feddit.de/c/schweiz) 

Eine ausführliche Sidebar findet ihr hier: [Infothread: Regeln, Feedback &amp; sonstige Infos](https://feddit.de/post/1320812)

Auch hier gelten die Serverregeln von https://feddit.de !

Banner: [SirSamuelVimes](https://feddit.de/u/SirSamuelVimes) , removed=false, published=2023-06-12T09:11:26.812895, updated=2023-08-30T13:42:12.701351, deleted=false, nsfw=false, actor_id=https://feddit.de/c/dach, local=true, icon=https://feddit.de/pictrs/image/0920d164-52d7-4fbd-b594-ae3b6266d55a.png, banner=https://feddit.de/pictrs/image/f9e48f65-8d84-45d0-a46a-867cb780861b.jpeg, hidden=false, posting_restricted_to_mods=false, instance_id=142) cannot be saved using the current SaveableStateRegistry. The default implementation only supports types which can be stored inside the Bundle. Please consider implementing a custom Saver for this class and pass it as a stateSaver parameter to rememberSaveable().
	at com.jerboa.UtilsKt$border$1.invoke(SourceFile:12)
	at com.jerboa.UtilsKt$border$1.invoke(SourceFile:83)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Unknown Source:4)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Unknown Source:135)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Unknown Source:82)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Unknown Source:5)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Unknown Source:171)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(Unknown Source:47)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@e27d5e0, androidx.compose.ui.platform.MotionDurationScaleImpl@5608099, StandaloneCoroutine{Cancelling}@9b8f5e, AndroidUiDispatcher@89edf3f]

```

**Comment by MV-GH** [comment]
Fixed in 0.0.52
