### ISSUE TITLE
App Crashes When Attempting to Login an Account

### ISSUE THREAD

**Issue by 0hCome0n** [dessalines/jerboa#1298]
### Jerboa Version

0.0.50

### Android Version + Phone

14 (AP11.231117.006) Pixel 7

### Describe The Bug

When logging into an account on Midwest.Social using the login page, the app crashes after a second or two. The app DOES NOT crash with an invalid login. Nor does it happen on beehaw.org

I believe it is related to Lemmy 0.19

### To Reproduce

1. Pull out side bar
2. Drop down account tab
3. Select add account
4. Login to just Midwest.Social
5. App Crashes and closes

### In the case of a crash or when relevant include the logs

`` Stacktrace ``

java.lang.IllegalStateException: You must either set a text or a view
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:216)
	at android.widget.Toast.show(Toast.java:198)
	at com.jerboa.model.LoginViewModel$login$1.invokeSuspend(Unknown Source:637)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8470)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8e31cbe, Dispatchers.Main.immediate]

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 40
Thread time: 0 hr 0 min, 6 sec

`` END of thread info ``

`` Device info ``

Report ID: 14508c91-0e38-4b8e-b0d3-6959f32b6cd4
Device ID: 5660af78b6500ad8
Application version: 50
Default launcher: com.android.settings
Timezone name: Eastern Standard Time
Timezone ID: America/New_York
Version release: 14
Version incremental : 11174680
Version SDK: 34
Board: panther
Bootloader: cloudripper-14.4-11000328
Brand: google
CPU ABIS 32: N/A
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a
Device: panther
Display: AP11.231117.006
Fingerprint: google/panther_beta/panther:14/AP11.231117.006/11174680:user/release-keys
Hardware: panther
Host: abfarm-release-rbe-32-2004-00110
ID: AP11.231117.006
Manufacturer: Google
Product: panther_beta
Build time: 1701719822000
Build time formatted: 04-12-2023 14:57:02
Type: user
Radio: g5300q-231116-231120-B-11122764,g5300q-231116-231120-B-11122764
Tags: release-keys
User: android-build
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: No
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 40
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: N/A
Number of CPU cores: 8
Up time with sleep: 15 hr 43 min, 32 sec
Up time without sleep: 10 hr 7 min, 14 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: crash
Importance: FOREGROUND
Reason: CRASH
Timestamp: 17-12-2023 00:49:12
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: FREEZER BINDER ASYNC FULL Async binder space running out while frozen
Importance: CACHED
Reason: N/A
Timestamp: 16-12-2023 18:42:31
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: FREEZER BINDER ASYNC FULL Async binder space running out while frozen
Importance: CACHED
Reason: N/A
Timestamp: 16-12-2023 11:27:07
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Jerboa
Version code: 50
Version name: 0.0.50
Package name: com.jerboa
Short package name: jerboa
Flavor: N/A
Signatures: nORRaWmGNmrBj18PL/p3svEr/s4=
Is debuggable: No
First installed: 31-05-2023 16:14:31
Last updated: 03-11-2023 09:27:04
Requested permissions: android.permission.ACCESS_NETWORK_STATE, android.permission.INTERNET, android.permission.READ_MEDIA_AUDIO, android.permission.READ_MEDIA_IMAGES, android.permission.READ_MEDIA_VIDEO, com.jerboa.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION, android.permission.READ_MEDIA_VISUAL_USER_SELECTED
Default prefs: N/A
Default prefs: N/A

`` END of Application info ``

`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

**Comment by 0hCome0n** [comment]
God damn it, literally the next thing I do is look at a post that mentions in the comments how jeroba 0.50 and Lemmy 0.19 don't play together, but jeroba 0.52 can handle it.

Nevermind.
