### ISSUE TITLE
Jwt expired, login again fails

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1424]
When receiving, JWT expired snackbar with login again action, pressing it will redirect you to login. But on login it will fail with already logged in. 

This case was expected and handled already be deleting it.

Backing out will show that is like current account is still that one that should be gone. Upon switching the account seems to br filly gone and logging in again works.

This is very strange

**Comment by dessalines** [comment]
I've noticed this too, but only on voyager.lemmy.ml , is that where you're getting this?

**Comment by MV-GH** [comment]
Somehow `allAccounts = repository.allAccounts` in accountViewModel still has the oldAccount for a while, it must not actually exist anymore because a simple swaps shows that it isn't listed anymore

**Comment by anibyl** [comment]
Log:
```
```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.240205.002/2024030300:user/release-keys
package: com.jerboa:50
process: com.jerboa
processUptime: 14097 + 200 ms

java.lang.IllegalStateException: You must either set a text or a view
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:215)
	at android.widget.Toast.show(Toast.java:199)
	at com.jerboa.model.LoginViewModel$login$1.invokeSuspend(Unknown Source:637)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ab93c8c, Dispatchers.Main.immediate]
```

```

**Comment by MV-GH** [comment]
What action did you do to get this exception? And thx for providing this stacktrace

**Comment by anibyl** [comment]
@MV-GH yes, I'm using 0.0.50. Apparently F-Droid wasn't updating it because newer builds were signed by a different key?.. Will update today, thanks!

**Comment by MV-GH** [comment]
The key hasn't changed, either you must have installed it from a different source (playstore or manually)
