### ISSUE TITLE
Saving vidoes fails

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1427]
### Jerboa Version

0.0.60

### Android Version + Phone

Android 12

### Describe The Bug

Try to save a video from the imageviewer or the long click (save action). Even tho video viewing isn't supported yet. Saving them originally was intended to work and the infra is there for it. 

### To Reproduce

Go to this comment https://lemmy.world/comment/8147476 (or this video https://lemmy.world/pictrs/image/54712746-6e15-4dd0-b538-fe774f52d9d5.webm)

Try to save it through long click -> save
or open it up and try to save it

Different causes each

### In the case of a crash or when relevant include the logs

When saving from image viewer
```
invalid URL
                 java.lang.IllegalArgumentException: MIME type video/webm cannot be inserted into content://media/external/images/media; expected MIME type under image/*
                 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
                 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
                 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
                 	at android.content.ContentResolver.insert(ContentResolver.java:2193)
                 	at android.content.ContentResolver.insert(ContentResolver.java:2155)
                 	at com.jerboa.UtilsKt.saveMediaQ(Utils.kt:892)
                 	at com.jerboa.feat.UserActionsKt$saveMedia$2.invokeSuspend(UserActions.kt:80)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

When saving from save action in long click (This one should def work)

```
invalid URL
                 java.lang.IllegalArgumentException: Primary directory Documents not allowed for content://media/external/downloads; allowed directories are [Download]
                 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
                 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
                 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
                 	at android.content.ContentResolver.insert(ContentResolver.java:2193)
                 	at android.content.ContentResolver.insert(ContentResolver.java:2155)
                 	at com.jerboa.UtilsKt.saveMediaQ(Utils.kt:892)
                 	at com.jerboa.feat.UserActionsKt$saveMedia$2.invokeSuspend(UserActions.kt:80)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

```

**Comment by dessalines** [comment]
Weird, why is it treating webm so differently.

**Comment by MV-GH** [comment]
it was a webm video, which must use the video/* mime type.

I have solved the bottom stacktrace though. I wasn't aware the directory needs to match the one specified in the mediastore content uri
