### ISSUE TITLE
App crahes on launch

### ISSUE THREAD

**Issue by zeitrechnen** [dessalines/jerboa#238]
Version: 0.0.19 (from F-Droid)
OS: GrapheneOS (Android 13, Security Patch October 5)

While version 0.0.17 works without any problems, version 0.0.19 always crashes when launching the app. Re-installing did not help.

Log: 

```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221005.003/2022101500:user/release-keys
package: com.jerboa:18
process: com.jerboa

java.lang.ExceptionInInitializerError
at com.jerboa.MainActivity.onCreate(Unknown Source:52)
at android.app.Activity.performCreate(Activity.java:8341)
at android.app.Activity.performCreate(Activity.java:8320)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1389)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3658)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3814)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7904)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.util.MissingResourceException: Can't find resource for bundle org.ocpsoft.prettytime.i18n.Resources, key ePattern
at java.util.ResourceBundle.getObject(ResourceBundle.java:448)
at java.util.ResourceBundle.getObject(ResourceBundle.java:442)
at java.util.ResourceBundle.getString(ResourceBundle.java:405)
at org.ocpsoft.prettytime.i18n.Resources_de$DeTimeFormat. (Unknown Source:17)
at org.ocpsoft.prettytime.i18n.Resources_de.a(Unknown Source:2)
at h8.b.j(Unknown Source:31)
at h8.b.c(Unknown Source:0)
at f8.e.j(Unknown Source:37)
at f8.e.a(Unknown Source:7)
at f8.e. (Unknown Source:24)
at p4.f0. (Unknown Source:6)
... 19 more

```

**Comment by dessalines** [comment]
Thanks, seems to be [this issue](https://github.com/ocpsoft/prettytime/issues/68) with prettytime and proguard. I'll add those lines and make you a test build in a minute.

**Comment by dessalines** [comment]
@zeitrechnen Could you test this out?

https://file.io/2jKlrUQJFdCZ

**Comment by zeitrechnen** [comment]
@dessalines Thanks you, but there is no file behind the link: The transfer you requested has been deleted.

**Comment by dessalines** [comment]
[app-release.zip](https://github.com/dessalines/jerboa/files/9805916/app-release.zip)

**Comment by zeitrechnen** [comment]
@dessalines Many thanks, with the version the problem is solved.

**Comment by dessalines** [comment]
Thanks, I'll start another release, will probably be on f-droid in about a week.
