### ISSUE TITLE
New version 0.0.22 won't start

### ISSUE THREAD

**Issue by l4nc3l0t** [dessalines/jerboa#264]
Since the last update when I try to launch jerboa there is no effect and I have a message who said that the app keeps stopping.

Don't know if it's a problem with my device but I open an issue in case it isn't.

**Comment by somehare** [comment]
Same problem here. Here is my crash report:

```
FATAL EXCEPTION: main
Process: com.jerboa, PID: 13067
android.content.res.Resources$NotFoundException: Resource ID #0x106002c
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:276)
	at android.content.res.Resources.getColor(Resources.java:1083)
	at d0.u0.a(Unknown Source:13)
	at w6.a.D0(Unknown Source:106)
	at w5.c.a(Unknown Source:125)
	at r.e1.a(Unknown Source:349)
	at r.e1.c0(Unknown Source:91)
	at n0.b.c0(Unknown Source:58)
	at androidx.compose.ui.platform.z0.a(Unknown Source:24)
	at r.e1.a(Unknown Source:407)
	at r.e1.c0(Unknown Source:115)
	at n0.b.c0(Unknown Source:58)
	at w6.a.f(Unknown Source:183)
	at androidx.compose.ui.platform.b1.a(Unknown Source:285)
	at o.w.a(Unknown Source:157)
	at o.w.c0(Unknown Source:113)
	at n0.b.c0(Unknown Source:58)
	at w6.a.f(Unknown Source:183)
	at androidx.compose.ui.platform.j0.a(Unknown Source:517)
	at androidx.compose.ui.platform.y2.a(Unknown Source:33)
	at androidx.compose.ui.platform.y2.c0(Unknown Source:16)
	at n0.b.c0(Unknown Source:58)
	at w6.a.f(Unknown Source:183)
	at androidx.compose.ui.platform.y2.a(Unknown Source:186)
	at androidx.compose.ui.platform.y2.c0(Unknown Source:28)
	at n0.b.c0(Unknown Source:58)
	at o.f2.b(Unknown Source:352)
	at o.f2.o(Unknown Source:165)
	at w6.a.C1(Unknown Source:42)
	at g0.u.n(Unknown Source:124)
	at g0.u.h(Unknown Source:13)
	at g0.z.m(Unknown Source:17)
	at g0.s1.a(Unknown Source:38)
	at g0.z.i(Unknown Source:10)
	at androidx.compose.ui.platform.z2.k0(Unknown Source:109)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(Unknown Source:11)
	at androidx.compose.ui.platform.WrappedComposition.i(Unknown Source:13)
	at androidx.compose.ui.platform.WrappedComposition.d(Unknown Source:18)
	at androidx.lifecycle.t.a(Unknown Source:17)
	at androidx.lifecycle.u.a(Unknown Source:114)
	at androidx.compose.ui.platform.z2.k0(Unknown Source:78)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(Unknown Source:108)
	at android.view.View.dispatchAttachedToWindow(View.java:21304)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4239)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2568)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2222)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9123)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
	at android.view.Choreographer.doFrame(Choreographer.java:732)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by poVoq** [comment]
See: https://slrpnk.net/post/198373

Seems to be only a problem on Android 11 or earlier?

**Comment by guillaume-uH57J9** [comment]
Hi! 

I also got a crash since I upgraded to Jerboa 0.0.22 on Android 11. 
In the short term, could you mark 0.0.22 as incompatible with Android 11 in F-Droid? That would avoid more users from getting crash, and give more time to investigate a fix. 

Here's the callstack captured using Scoop. 
It looks identical to the one from @somehare 

```
FATAL EXCEPTION: main
Process: com.jerboa, PID: 32125
android.content.res.Resources$NotFoundException: Resource ID #0x106002b
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
	at android.content.res.Resources.getColor(Resources.java:1059)
	at d0.u0.a(Unknown Source:13)
	at w6.a.D0(Unknown Source:100)
	at w5.c.a(Unknown Source:125)
	at r.e1.a(Unknown Source:349)
	at r.e1.c0(Unknown Source:91)
	at n0.b.c0(Unknown Source:58)
	at androidx.compose.ui.platform.z0.a(Unknown Source:24)
	at r.e1.a(Unknown Source:407)
	at r.e1.c0(Unknown Source:115)
	at n0.b.c0(Unknown Source:58)
	at w6.a.f(Unknown Source:183)
	at androidx.compose.ui.platform.b1.a(Unknown Source:285)
	at o.w.a(Unknown Source:157)
	at o.w.c0(Unknown Source:113)
	at n0.b.c0(Unknown Source:58)
	at w6.a.f(Unknown Source:183)
	at androidx.compose.ui.platform.j0.a(Unknown Source:517)
	at androidx.compose.ui.platform.y2.a(Unknown Source:33)
	at androidx.compose.ui.platform.y2.c0(Unknown Source:16)
	at n0.b.c0(Unknown Source:58)
	at w6.a.f(Unknown Source:183)
	at androidx.compose.ui.platform.y2.a(Unknown Source:186)
	at androidx.compose.ui.platform.y2.c0(Unknown Source:28)
	at n0.b.c0(Unknown Source:58)
	at o.f2.b(Unknown Source:352)
	at o.f2.o(Unknown Source:165)
	at w6.a.C1(Unknown Source:42)
	at g0.u.n(Unknown Source:124)
	at g0.u.h(Unknown Source:13)
	at g0.z.m(Unknown Source:17)
	at g0.s1.a(Unknown Source:38)
	at g0.z.i(Unknown Source:10)
	at androidx.compose.ui.platform.z2.k0(Unknown Source:109)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(Unknown Source:11)
	at androidx.compose.ui.platform.WrappedComposition.i(Unknown Source:13)
	at androidx.compose.ui.platform.WrappedComposition.d(Unknown Source:18)
	at androidx.lifecycle.t.a(Unknown Source:17)
	at androidx.lifecycle.u.a(Unknown Source:114)
	at androidx.compose.ui.platform.z2.k0(Unknown Source:78)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(Unknown Source:108)
	at android.view.View.dispatchAttachedToWindow(View.java:20483)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2437)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1950)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8186)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
	at android.view.Choreographer.doCallbacks(Choreographer.java:878)
	at android.view.Choreographer.doFrame(Choreographer.java:811)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by guillaume-uH57J9** [comment]
I double-checked this is indeed a regression.
After uninstalling 0.0.22 and re-installing 0.0.21 on Android 11, the application works again.

**Comment by dessalines** [comment]
I should be able to get to this within a few days. Hopefully its a common problem with material 3 with an easy fix.

**Comment by poVoq** [comment]
New version today from F-Droid works indeed on Android 11. Thanks for fixing it!
