### ISSUE TITLE
App crashing while seeing comment 

### ISSUE THREAD

**Issue by DLRAM** [dessalines/jerboa#363]
I am using Android 10

**Comment by dessalines** [comment]
Could you post a crash log? Or replicate how you got there?

**Comment by jaamulberry** [comment]
It seems that if you don't login and click on the first post if you scroll to comments the app crashes.

**Comment by dessalines** [comment]
Someone else made a crash log. It seems to only happen on a specific comment:

```
type: crash
osVersion: google/bluejay/bluejay:13/TQ2A.230505.002/2023052900:user/release-keys
package: com.jerboa:30
process: com.jerboa
processUptime: 4067 + 191 ms

java.lang.IllegalArgumentException: Padding must be non-negative
	at r.u0.<init>(Unknown Source:72)
	at f1.c.y0(Unknown Source:28)
	at d5.j.X(Unknown Source:173)
	at n0.b.a(Unknown Source:50)
	at n0.b.X(Unknown Source:8)
	at s.j0.T(Unknown Source:181)
	at n0.b.b(Unknown Source:50)
	at n0.b.T(Unknown Source:8)
	at o.t.a(Unknown Source:2503)
	at o.t.Y(Unknown Source:317)
	at n0.b.Y(Unknown Source:58)
	at f7.i.t(Unknown Source:182)
	at x.c1.k(Unknown Source:182)
	at s.t.T(Unknown Source:152)
	at n0.b.b(Unknown Source:50)
	at n0.b.T(Unknown Source:8)
	at t.c.g(Unknown Source:80)
	at s.v.g(Unknown Source:61)
	at t.a.g(Unknown Source:67)
	at s.w.g(Unknown Source:12)
	at n.l0.a(Unknown Source:169)
	at n.l0.Y(Unknown Source:161)
	at n0.b.Y(Unknown Source:58)
	at f7.i.t(Unknown Source:182)
	at p0.h.f(Unknown Source:113)
	at t.k0.f(Unknown Source:32)
	at t.n.Y(Unknown Source:134)
	at n0.b.Y(Unknown Source:58)
	at p.h0.b(Unknown Source:1524)
	at p.h0.Y(Unknown Source:165)
	at n0.b.Y(Unknown Source:58)
	at o.e2.b(Unknown Source:372)
	at o.e2.o(Unknown Source:48)
	at f7.i.S1(Unknown Source:42)
	at g0.w.o(Unknown Source:128)
	at g0.w.i(Unknown Source:13)
	at g0.c0.m(Unknown Source:17)
	at g0.w1.a(Unknown Source:38)
	at g0.l.a(Unknown Source:9)
	at g0.l.a(Unknown Source:9)
	at g0.c0.g(Unknown Source:10)
	at k1.b0.c(Unknown Source:101)
	at k1.x.a(Unknown Source:134)
	at s.s0.a(Unknown Source:49)
	at s.d0.Y(Unknown Source:693)
	at t.n.Y(Unknown Source:175)
	at k1.z.d(Unknown Source:47)
	at m1.t.b(Unknown Source:36)
	at o.g.f(Unknown Source:58)
	at o.g.X(Unknown Source:477)
	at k1.v.e(Unknown Source:12)
	at m1.a0.b(Unknown Source:10)
	at o.g.f(Unknown Source:19)
	at o.g.X(Unknown Source:490)
	at k1.v.e(Unknown Source:12)
	at m1.a0.b(Unknown Source:10)
	at x0.h0.e(Unknown Source:5)
	at m1.a0.b(Unknown Source:10)
	at r.x0.e(Unknown Source:108)
	at m1.e.e(Unknown Source:14)
	at m1.a0.b(Unknown Source:10)
	at m1.j0.a(Unknown Source:47)
	at m1.j0.o(Unknown Source:6)
	at d0.j6.d(Unknown Source:63)
	at o.y0.b(Unknown Source:339)
	at o.y0.o(Unknown Source:69)
	at f7.i.S1(Unknown Source:42)
	at q0.z.c(Unknown Source:117)
	at m1.m1.a(Unknown Source:12)
	at m1.m0.C0(Unknown Source:116)
	at m1.r0.c(Unknown Source:54)
	at m1.r0.j(Unknown Source:124)
	at m1.r0.d(Unknown Source:52)
	at m1.m0.C0(Unknown Source:56)
	at m1.m0.b(Unknown Source:145)
	at d0.y4.j0(Unknown Source:821)
	at k1.g0.e(Unknown Source:32)
	at k1.y.e(Unknown Source:8)
	at o.e2.b(Unknown Source:150)
	at o.e2.o(Unknown Source:40)
	at d0.j6.d(Unknown Source:63)
	at o.y0.b(Unknown Source:339)
	at o.y0.o(Unknown Source:69)
	at f7.i.S1(Unknown Source:42)
	at q0.z.c(Unknown Source:117)
	at m1.m1.a(Unknown Source:12)
	at m1.m0.g(Unknown Source:131)
	at m1.t.v0(Unknown Source:126)
	at k1.t0.c(Unknown Source:32)
	at m1.l0.o(Unknown Source:14)
	at d0.j6.d(Unknown Source:63)
	at o.y0.b(Unknown Source:339)
	at o.y0.o(Unknown Source:69)
	at f7.i.S1(Unknown Source:42)
	at q0.z.c(Unknown Source:117)
	at m1.m1.a(Unknown Source:12)
	at m1.m0.B0(Unknown Source:60)
	at m1.g0.O(Unknown Source:26)
	at m1.r0.j(Unknown Source:212)
	at m1.r0.f(Unknown Source:70)
	at androidx.compose.ui.platform.AndroidComposeView.q(Unknown Source:13)
	at m1.k1.a(Unknown Source:3)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:18)
	at android.view.View.draw(View.java:23220)
	at android.view.View.updateDisplayListIfDirty(View.java:22084)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4764)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4475)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3662)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2346)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7903)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```
