### ISSUE TITLE
Instant crash on first run if no Internet access

### ISSUE THREAD

**Issue by Sophira** [dessalines/jerboa#378]
I'm using the F-Droid build of Jerboa 0.0.30 on GrapheneOS (Android 13) on a Pixel 7.

**Obviously, I realise that Jerboa by its very nature requires Internet access to work.** However, I tend to try launching new apps without Internet access to see how they react. In Jerboa's case, the answer is that it crashes instantly on launch while displaying the "Support Jerboa" box, without any explanation, when trying to connect to GitHub. (Presumably while [trying to access the RELEASES.md file](https://github.com/dessalines/jerboa/blob/0.0.30/app/src/main/java/com/jerboa/ui/components/common/Dialogs.kt#L303-L311).)

In this case, I would expect Jerboa to instead just not be able to load the changelog at all and to let the user know, but let the user pass if they were okay with doing so. Crashing instantly means that it's not very obvious at all what the problem is.

The exception is as follows (in this case, with Wifi and Data access turned off; a different error occurs if the Internet access is blocked completely by using AFWall+, but the resolution is the same - allow Internet access):

```
type: crash
osVersion: google/panther/panther:13/TQ2A.230505.002/2023050100:user/release-keys
package: com.jerboa:30
process: com.jerboa
processUptime: 259 + 235 ms

java.net.UnknownHostException: Unable to resolve host "raw.githubusercontent.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:147)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at m1.f.i(Unknown Source:5)
	at x7.a.a(Unknown Source:451)
	at y7.g.b(Unknown Source:138)
	at v7.a.a(Unknown Source:120)
	at y7.g.b(Unknown Source:138)
	at y7.a.a(Unknown Source:174)
	at y7.g.b(Unknown Source:138)
	at y7.h.a(Unknown Source:153)
	at y7.g.b(Unknown Source:138)
	at x7.k.i(Unknown Source:95)
	at x7.k.f(Unknown Source:41)
	at i5.u.h(Unknown Source:98)
	at y6.a.j(Unknown Source:8)
	at p7.f0.run(Unknown Source:104)
	at kotlinx.coroutines.internal.g.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(Unknown Source:76)
	Suppressed: e4.f: [androidx.compose.ui.platform.s1@9d9b799, g0.f@f9fa5e, p1{Cancelling}@76c6e3f, Dispatchers.IO]
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 19 more

```

**Comment by dessalines** [comment]
Agree, at the very least that popup should fail silently.
