### ISSUE TITLE
Crash when trying to save an image

### ISSUE THREAD

**Issue by vivia** [dessalines/jerboa#688]
** Jerboa Version **
0.0.34

**Describe the bug**
The application crashes when trying to save an image

**To Reproduce**

(0. Grant the Storage permission to the app)
1. Go to any timeline
2. Click on any image
3. Click the Download button on the top right
4. The application suddenly closes without saving the image

Using /e/OS Android 9 on Fairphone 3. Had it installed previously via F-Droid, issue was still there, this is from IzzyOnDroid.

**Comment by MV-GH** [comment]
We are gonna need the logs bc i cant reproduce this.

**Comment by vivia** [comment]
Sure, how can I get the logs?

**Comment by MV-GH** [comment]
https://android.stackexchange.com/questions/14430/how-can-i-view-and-examine-the-android-log

**Comment by vivia** [comment]
```
06-16 02:17:13.452 14776 14776 E AndroidRuntime: FATAL EXCEPTION: main
06-16 02:17:13.452 14776 14776 E AndroidRuntime: Process: com.jerboa, PID: 14776
06-16 02:17:13.452 14776 14776 E AndroidRuntime: java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=14776, uid=10196 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1950)
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1918)
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	at android.content.ContentResolver.insert(ContentResolver.java:1588)
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	at t4.o0.z(Unknown Source:51)
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	at c5.c0.k(Unknown Source:30)
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	at l6.a.z(Unknown Source:8)
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	at c7.d0.run(Unknown Source:109)
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	at b6.d.run(Unknown Source:13)
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	at i7.i.run(Unknown Source:2)
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	at i7.a.run(Unknown Source:93)
06-16 02:17:13.452 14776 14776 E AndroidRuntime: 	Suppressed: h7.f: [androidx.compose.ui.platform.u1@e8ae756, d0.f@624e3d7, m1{Cancelling}@a6ab4c4, u0@61adfad]
06-16 02:17:13.455  1176  1659 W ActivityManager:   Force finishing activity com.jerboa/.MainActivity
06-16 02:17:13.500  1176  1371 I ActivityManager: Showing crash dialog for package com.jerboa u0
06-16 02:17:13.537   488   488 I chatty  : uid=1000(system) /system/bin/surfaceflinger identical 10 lines
06-16 02:17:13.537   488   488 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
06-16 02:17:13.544  1176  5819 I OpenGLRenderer: Initialized EGL, version 1.4
06-16 02:17:13.544  1176  5819 D OpenGLRenderer: Swap behavior 2
06-16 02:17:13.555   488   488 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
06-16 02:17:13.961  1176  1370 W ActivityManager: Activity pause timeout for ActivityRecord{d20b342 u0 com.jerboa/.MainActivity t7258 f}
06-16 02:17:13.970  1176  1370 D NetworkManagement: Uid 10129 restricted because of app standby mode
06-16 02:17:13.970  1176  1370 D NetworkManagement: Uid 10097 restricted because of app standby mode
06-16 02:17:13.970  1176  1370 D NetworkManagement: Uid 10038 restricted because of app standby mode
06-16 02:17:13.986  1176  1370 D NetworkManagement: Uid 10129 restricted because of app standby mode
06-16 02:17:13.987  1176  1370 D NetworkManagement: Uid 10097 restricted because of app standby mode
06-16 02:17:13.987  1176  1370 D NetworkManagement: Uid 10038 restricted because of app standby mode
06-16 02:17:14.073  1176  1265 D NetworkManagement: Uid 10129 restricted because of app standby mode
06-16 02:17:14.073  1176  1265 D NetworkManagement: Uid 10097 restricted because of app standby mode
06-16 02:17:14.073  1176  1265 D NetworkManagement: Uid 10038 restricted because of app standby mode
06-16 02:17:14.078  1176  1370 D NetworkManagement: Uid 10129 restricted because of app standby mode
06-16 02:17:14.078  1176  1370 D NetworkManagement: Uid 10097 restricted because of app standby mode
06-16 02:17:14.078  1176  1370 D NetworkManagement: Uid 10038 restricted because of app standby mode
06-16 02:17:14.079  1176  1370 D NetworkManagement: Uid 10129 restricted because of app standby mode
06-16 02:17:14.079  1176  1370 D NetworkManagement: Uid 10097 restricted because of app standby mode
06-16 02:17:14.079  1176  1370 D NetworkManagement: Uid 10038 restricted because of app standby mode
06-16 02:17:14.080  1176  1578 D NetworkManagement: oldRule = 0, newRule=0 for uid=10196 on chain 2
06-16 02:17:14.081  1176  1578 D NetworkManagement: !!!!! Skipping change
06-16 02:17:14.237   488   488 I chatty  : uid=1000(system) /system/bin/surfaceflinger identical 118 lines
```

![Screenshot_20230616-021802_Package_installer](https://github.com/dessalines/jerboa/assets/28337/b9893ff7-9f60-4947-8c34-d441bf831550)

It seems to be complaining about a missing permission but I don't see where I could have enabled it.

**Comment by MV-GH** [comment]
Someone removed these since they dont do work anymore for android 11+ but android 9 still needs them. Ill make a build with it and post it here. Can you check then if it solves the issue?

**Comment by vivia** [comment]
Sure!

**Comment by MV-GH** [comment]
[app-release.zip](https://github.com/dessalines/jerboa/files/11764004/app-release.zip)
Alright can you try it out?

**Comment by vivia** [comment]
Unfortunately it didn't work, it behaves exactly the same. I also don't see any additional permissions I can grant.

**Comment by MV-GH** [comment]
I see, I also need to explicitly request the permission. Ill write something up and post it here again

**Comment by MV-GH** [comment]
[app-release.zip](https://github.com/dessalines/jerboa/files/11764273/app-release.zip)

Alright wrote something quickly, havent had chance to test it yet. Android 9 sdk taking forever to download

**Comment by MV-GH** [comment]
[app-release.zip](https://github.com/dessalines/jerboa/files/11770137/app-release.zip

This should work tested it on android 8, 9, 10 ,11 ,13

**Comment by vivia** [comment]
Thanks! I can confirm it doesn't crash now and says "Saved picture". But I can't find where, it's not on my Gallery.

**Comment by MV-GH** [comment]
I might get that to work https://developer.android.com/reference/android/media/MediaScannerConnection#scanFile(java.lang.String,%20java.lang.String)

**Comment by vivia** [comment]
Ah that looks like it would work, Gallery recognised it after I opened one picture!
