### ISSUE TITLE
Crash when trying to log in

### ISSUE THREAD

**Issue by Snow4DV** [dessalines/jerboa#782]
**Jerboa Version**
Compiled from main branch

**Describe the bug**
Crash when trying to log in while using latest version from main branch

**To Reproduce**

1. Open app
2. Try to log in

**In the case of a crash**
```
FATAL EXCEPTION: main
                                                                                                    Process: com.jerboa.debug, PID: 29893
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.jerboa.datatypes.types.ListingType.ordinal()' on a null object reference
                                                                                                    	at com.jerboa.ui.components.login.LoginViewModel$login$1.invokeSuspend(LoginViewModel.kt:103)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:233)
                                                                                                    	at android.os.Looper.loop(Looper.java:344)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8212)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8dbb41d, Dispatchers.Main.immediate]
2023-06-21 02:23:15.656 29893-29893 Process                 com.jerboa.debug                     I  Sending signal. PID: 29893 SIG: 9
```

So by some reason site response returns null default_listing_type and default_sorting_type. That wasn't a thing in the past versions like 0.0.34. Didn't have time to figure it out yet.

**Comment by MV-GH** [comment]
That's normal the main supports now only 0.18 lemmy servers so logging doesn't work, change the default instance to voyager.lemmy.ml. See #737

**Comment by Snow4DV** [comment]
Oh ok - missed it. Can be closed then. I do agree that it's a bad idea trying to support multiple versions of API at the time so updates are going to be a pain in the a soon until major version like 1.0 is released.
