### ISSUE TITLE
Crash on app open

### ISSUE THREAD

**Issue by ttmx** [dessalines/jerboa#839]
**Jerboa Version**
0.0.34

**Describe the bug**
Pressing the icon to open the app flashes a seemingly normal looking app and then crashes, maybe 600ms later.

**To Reproduce**
1. Attempt to open app
2. Observe crash

**In the case of a crash**

Please include the logs.
See [this post](https://android.stackexchange.com/questions/14430/how-can-i-view-and-examine-the-android-log) to get the logs.
`adb logcat com.jerboa` Should give you the relevant logs.

```
type: crash
osVersion: google/panther/panther:13/TQ3A.230605.012/2023061402:user/release-keys
package: com.jerboa:34
process: com.jerboa
processUptime: 788 + 570 ms

java.util.NoSuchElementException: Collection is empty.
	at c7.w.y1(Unknown Source:64)
	at k.u.c(Unknown Source:77)
	at k.u.Y(Unknown Source:34)
	at k0.b.a(Unknown Source:50)
	at k0.b.Y(Unknown Source:8)
	at q.j0.Q(Unknown Source:181)
	at k0.b.b(Unknown Source:50)
	at k0.b.Q(Unknown Source:8)
	at m.s.a(Unknown Source:2322)
	at m.s.Z(Unknown Source:317)
	at k0.b.Z(Unknown Source:58)
	at s6.i.g(Unknown Source:182)
	at d6.a.t(Unknown Source:182)
	at q.t.Q(Unknown Source:292)
	at k0.b.b(Unknown Source:50)
	at k0.b.Q(Unknown Source:8)
	at r.c.g(Unknown Source:80)
	at q.v.g(Unknown Source:61)
	at r.a.g(Unknown Source:67)
	at q.w.g(Unknown Source:12)
	at l.l0.a(Unknown Source:149)
	at l.l0.Z(Unknown Source:137)
	at k0.b.Z(Unknown Source:58)
	at s6.i.g(Unknown Source:182)
	at m0.h.e(Unknown Source:114)
	at r.k0.e(Unknown Source:32)
	at r.n.Z(Unknown Source:134)
	at k0.b.Z(Unknown Source:58)
	at n.h0.b(Unknown Source:1183)
	at n.h0.Z(Unknown Source:141)
	at k0.b.Z(Unknown Source:58)
	at m.d2.b(Unknown Source:371)
	at m.d2.u(Unknown Source:48)
	at s6.i.W0(Unknown Source:42)
	at d0.w.o(Unknown Source:128)
	at d0.w.i(Unknown Source:13)
	at d0.c0.m(Unknown Source:17)
	at d0.y1.a(Unknown Source:38)
	at d0.l.a(Unknown Source:9)
	at d0.l.a(Unknown Source:9)
	at d0.c0.i(Unknown Source:10)
	at h1.b0.c(Unknown Source:101)
	at h1.x.a(Unknown Source:134)
	at q.s0.a(Unknown Source:49)
	at q.d0.Z(Unknown Source:693)
	at r.n.Z(Unknown Source:175)
	at h1.z.b(Unknown Source:47)
	at j1.t.b(Unknown Source:36)
	at m.g.f(Unknown Source:58)
	at m.g.Y(Unknown Source:477)
	at h1.v.d(Unknown Source:12)
	at j1.a0.b(Unknown Source:10)
	at m.g.f(Unknown Source:19)
	at m.g.Y(Unknown Source:490)
	at h1.v.d(Unknown Source:12)
	at j1.a0.b(Unknown Source:10)
	at u0.g0.d(Unknown Source:5)
	at j1.a0.b(Unknown Source:10)
	at p.x0.d(Unknown Source:108)
	at j1.e.d(Unknown Source:14)
	at j1.a0.b(Unknown Source:10)
	at j1.j0.a(Unknown Source:47)
	at j1.j0.u(Unknown Source:6)
	at androidx.compose.material3.z2.d(Unknown Source:63)
	at m.w0.b(Unknown Source:269)
	at m.w0.u(Unknown Source:193)
	at s6.i.W0(Unknown Source:42)
	at n0.z.c(Unknown Source:117)
	at j1.m1.a(Unknown Source:12)
	at j1.m0.C0(Unknown Source:116)
	at j1.g0.L(Unknown Source:16)
	at j1.r0.c(Unknown Source:24)
	at j1.r0.j(Unknown Source:124)
	at j1.r0.f(Unknown Source:70)
	at androidx.compose.ui.platform.AndroidComposeView.s(Unknown Source:13)
	at j1.k1.a(Unknown Source:3)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:18)
	at android.view.View.draw(View.java:23269)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4785)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4496)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3683)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2367)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9293)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7937)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by MV-GH** [comment]
Lemmy updated to 0.18, jerboa 0.34 doesnt support it yet, update jerboa to 0.35

**Comment by ttmx** [comment]
Worked, but it wasn't on f-droid.
Thank you!
