### ISSUE TITLE
Jerboa keeps stopping at startup

### ISSUE THREAD

**Issue by jwdevelab** [dessalines/jerboa#843]
**Jerboa Version**
0.0.32 F-Droid
**Describe the bug**
Jerboa keeps stopping at startup on xiaomi redmi note 8 (2021)

**To Reproduce**

1. Go to Jerboa for Lemmy page on F-Droid 
2. Click on install then open
3. Jerboa stops and go back to F-Droid

**In the case of a crash**
```
java.util.NoSuchElementException: Collection is empty.
	at v2.f.m0(Unknown Source:64)
	at n.u.c(Unknown Source:122)
	at n.u.X(Unknown Source:33)
	at n0.b.a(Unknown Source:50)
	at n0.b.X(Unknown Source:8)
	at t.j0.S(Unknown Source:181)
	at n0.b.b(Unknown Source:50)
	at n0.b.S(Unknown Source:8)
	at p.s.a(Unknown Source:2519)
	at p.s.Y(Unknown Source:317)
	at n0.b.Y(Unknown Source:58)
	at y.y0.c(Unknown Source:182)
	at c6.d.C(Unknown Source:182)
	at t.t.S(Unknown Source:152)
	at n0.b.b(Unknown Source:50)
	at n0.b.S(Unknown Source:8)
	at u.c.g(Unknown Source:80)
	at t.v.g(Unknown Source:61)
	at u.a.g(Unknown Source:67)
	at t.w.g(Unknown Source:12)
	at o.l0.a(Unknown Source:185)
	at o.l0.Y(Unknown Source:173)
	at n0.b.Y(Unknown Source:58)
	at y.y0.c(Unknown Source:182)
	at p0.h.f(Unknown Source:114)
	at u.k0.f(Unknown Source:32)
	at u.n.Y(Unknown Source:134)
	at n0.b.Y(Unknown Source:58)
	at q.h0.b(Unknown Source:1546)
	at q.h0.Y(Unknown Source:165)
	at n0.b.Y(Unknown Source:58)
	at p.d2.b(Unknown Source:387)
	at p.d2.o(Unknown Source:52)
	at y.y0.I0(Unknown Source:42)
	at g0.w.o(Unknown Source:128)
	at g0.w.i(Unknown Source:13)
	at g0.c0.m(Unknown Source:17)
	at g0.w1.a(Unknown Source:38)
	at g0.l.a(Unknown Source:9)
	at g0.l.a(Unknown Source:9)
	at g0.c0.i(Unknown Source:10)
	at k1.b0.c(Unknown Source:101)
	at k1.x.a(Unknown Source:134)
	at t.s0.a(Unknown Source:49)
	at t.d0.Y(Unknown Source:693)
	at u.n.Y(Unknown Source:175)
	at k1.z.d(Unknown Source:47)
	at m1.s.b(Unknown Source:36)
	at p.g.f(Unknown Source:58)
	at p.g.X(Unknown Source:477)
	at k1.v.e(Unknown Source:12)
	at m1.z.b(Unknown Source:10)
	at p.g.f(Unknown Source:19)
	at p.g.X(Unknown Source:490)
	at k1.v.e(Unknown Source:12)
	at m1.z.b(Unknown Source:10)
	at x0.g0.e(Unknown Source:5)
	at m1.z.b(Unknown Source:10)
	at s.x0.e(Unknown Source:108)
	at m1.e.e(Unknown Source:14)
	at m1.z.b(Unknown Source:10)
	at m1.i0.a(Unknown Source:47)
	at m1.i0.o(Unknown Source:6)
	at androidx.compose.material3.z1.d(Unknown Source:63)
	at p.x0.b(Unknown Source:339)
	at p.x0.o(Unknown Source:69)
	at y.y0.I0(Unknown Source:42)
	at q0.z.c(Unknown Source:117)
	at m1.l1.a(Unknown Source:12)
	at m1.l0.C0(Unknown Source:116)
	at m1.f0.M(Unknown Source:16)
	at m1.q0.c(Unknown Source:24)
	at m1.q0.j(Unknown Source:124)
	at m1.q0.f(Unknown Source:70)
	at androidx.compose.ui.platform.AndroidComposeView.s(Unknown Source:13)
	at m1.j1.a(Unknown Source:3)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:18)
	at android.view.View.draw(View.java:23492)
	at android.view.View.updateDisplayListIfDirty(View.java:22301)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:795)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4994)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4683)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3868)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2577)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9634)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1386)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1013)
	at android.view.Choreographer.doFrame(Choreographer.java:911)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1366)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
.

```

**Comment by MV-GH** [comment]
Lemmy.ml updated to 0.18, jerboa version below 0.35 doesn't support 0.18. I recommend upgrading.

**Comment by EnverOsmanov** [comment]
I had the same issue with version 0.0.33 from Google Play Store.

I installed Android Studio and run newer version over USB. tag 0.0.34 is also failing, but 0.0.35 is working just fine.

**Comment by MV-GH** [comment]
You can get the newer versions from github release page

**Comment by MV-GH** [comment]
Yes I know, play store is lagging behind on approving releases but there is nothing we can do about that. At least until we do beta play store program for our nightly build.

**Comment by jwdevelab** [comment]
Version 0.0.35-alpha from release page works just fine, thank you. Can I ask why F-Droid version is out of date then, I have no idea about maintaining F-Droid package, I'm just curious.

**Comment by MV-GH** [comment]
F droid takes a bit longer to approve

**Comment by jwdevelab** [comment]
Thanks, i guess we can close now.
