### ISSUE TITLE
Voting on post after opening instantly crashes app

### ISSUE THREAD

**Issue by Coffee-Viking** [dessalines/jerboa#852]
**Jerboa Version**
0.0.35

**Describe the bug**
Up or downvoting after opening a post crashes the app instantly.

**To Reproduce**

1. Open any post
2. Up- or downvote
3. Crash

Video: https://youtube.com/shorts/dDoSev2eZ8A?feature=share

**In the case of a crash**

FATAL EXCEPTION: main
Process: com.jerboa, PID: 22359
java.lang.NullPointerException: Parameter specified as non-null is null: method com.jerboa.datatypes.types.GetPostResponse.copy, parameter cross_posts
	at com.jerboa.datatypes.types.GetPostResponse.copy(Unknown Source:17)
	at com.jerboa.datatypes.types.GetPostResponse.copy$default(Unknown Source:40)
	at m5.b1.g(Unknown Source:34)
	at m5.y0.h(Unknown Source:86)
	at t6.a.k(Unknown Source:8)
	at k7.d0.run(Unknown Source:109)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8191)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: p7.f: [m1{Cancelling}@17d13cc, Dispatchers.Main.immediate]

Please let me know if the full log is required, but the rest looks fine.

**Comment by beatgammit** [comment]
Looks like #831, or something very related to it.

**Comment by beatgammit** [comment]
What instance are you on? And do you know what version of lemmy it runs?

I accessed that same post through a different lemmy instance on 0.18 and it worked fine. If that instance isn't on 0.18 yet, please retest when it upgrades since this could be a simple API versioning issue.

**Comment by Coffee-Viking** [comment]
I'm on latte.isnot.coffee, and as of yesterday it's still running 0.17.4, I believe the admin was going to update over the weekend. Will keep you posted and close the bug report if it's indeed a versioning issue.

**Comment by MV-GH** [comment]
Looks like it was due to not supported instance level
