### ISSUE TITLE
App v0.0.37 crashes when hitting "Back" in a post

### ISSUE THREAD

**Issue by scottwallacesh** [dessalines/jerboa#927]
**Jerboa Version**
0.0.37

**Android version + phone**
Android 13, Pixel 4a

**Describe the bug**
When reading a post and hitting the "Back" button, the app crashes.

**To Reproduce**
1. Read a post
2. Hit "Back"

**In the case of a crash**
<details><summary>LOGS</summary>

```text
--------- beginning of main
06-30 08:00:47.921 13116 13133 E OpenGLRenderer: Unable to match the desired swap behavior.
06-30 08:00:51.028 13116 13116 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
06-30 08:00:51.028 13116 13116 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
06-30 08:00:51.048 13116 13116 D jerboa  : got to post activity
06-30 08:00:51.073 13116 18031 I okhttp.OkHttpClient: --> GET https://lemmy.example.com/api/v3/post?auth=[AUTH_TOKEN]&id=[ID]
06-30 08:00:51.073 13116 18031 I okhttp.OkHttpClient: User-Agent: Jerboa
06-30 08:00:51.073 13116 18031 I okhttp.OkHttpClient: --> END GET
06-30 08:00:51.073 13116 13116 D Compose Focus: Owner FocusChanged(true)
06-30 08:00:51.088 13116 13116 D jerboa  : got to home activity
06-30 08:00:51.088 13116 13116 D jerboa  : got to post activity
06-30 08:00:51.121 13116 13116 D jerboa  : got to post activity
06-30 08:00:51.129 13116 18034 D TrafficStats: tagSocket(96) with statsTag=0xffffffff, statsUid=-1
06-30 08:00:51.805 13116 18031 I okhttp.OkHttpClient: <-- 200 https://lemmy.example.com/api/v3/post?auth=[AUTH_TOKEN]&id=[ID] (732ms)
06-30 08:00:51.805 13116 18031 I okhttp.OkHttpClient: content-type: application/json
06-30 08:00:51.806 13116 18031 I okhttp.OkHttpClient: date: Fri, 30 Jun 2023 07:00:51 GMT
06-30 08:00:51.806 13116 18031 I okhttp.OkHttpClient: permissions-policy: interest-cohort=()
06-30 08:00:51.806 13116 18031 I okhttp.OkHttpClient: strict-transport-security: max-age=31536000
06-30 08:00:51.806 13116 18031 I okhttp.OkHttpClient: vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
06-30 08:00:51.806 13116 18031 I okhttp.OkHttpClient: x-content-type-options: nosniff
06-30 08:00:51.806 13116 18031 I okhttp.OkHttpClient: x-download-options: noopen
06-30 08:00:51.806 13116 18031 I okhttp.OkHttpClient: x-permitted-cross-domain-policies: none
06-30 08:00:51.806 13116 18031 I okhttp.OkHttpClient: x-robots-tag: none
06-30 08:00:51.806 13116 18031 I okhttp.OkHttpClient: x-xss-protection: 1; mode=block
06-30 08:00:51.806 13116 18031 I okhttp.OkHttpClient: content-length: 10376
06-30 08:00:51.807 13116 18031 I okhttp.OkHttpClient: {"post_view":{"post":{"id":22984,"name":"Bigger bottles keep champagne bubbly for decades - American Chemical Society","url":"https://www.acs.org/pressroom/presspacs/2023/june/bigger-bottles-keep-champagne-bubbly-for-decades.html","creator_id":314,"community_id":66,"removed":false,"locked":false,"published":"2023-06-29T17:13:58.238286","deleted":false,"nsfw":false,"embed_title":"Bigger bottles keep champagne bubbly for decades - American Chemical Society","embed_description":"According to researchers reporting in ACS Omega, how long champagne and sparkling wines can be stored in sealed bottles before they go flat depends on the container’s size.","ap_id":"https://aussie.zone/post/210279","local":false,"language_id":37,"featured_community":false,"featured_local":false},"creator":{"id":314,"name":"withersailor","banned":false,"published":"2023-06-10T00:22:53.178988","actor_id":"https://aussie.zone/u/withersailor","local":false,"deleted":false,"admin":false,"bot_account":false,"instance_id":59},"community":{"id":66,"name":"science","title":"Science","description":"Studies, research findings, and interesting tidbits from the ever-expanding scientific world.\n\nSubcommunities on Beehaw:\n\n- [Space](https://beehaw.org/c/space)\n\n----\n \nBe sure to also check out these other Fediverse science communities:\n\n- https://lemmy.ml/c/science\n- https://mander.xyz/c/science\n\n---\n\nThis community's icon was made by Aaron Schneider, under the [CC-BY-NC-SA 4.0 license](https://creativecommons.org/licenses/by-nc-sa/4.0/).","removed":false,"published":"2022-01-28T17:11:23.955280","updated":"2023-06-16T19:32:02.245431","deleted":false,"nsfw":false,"actor_id":"https://beehaw.org/c/science","local":false,"icon":"https://beehaw.org/pictrs/image/f83a7ff8-4e85-47a3-b4df-6a814e29c5d4.png","hidden":false,"posting_restricted_to_mods":false,"instance_id":16},"creator_banned_from_community":false,"counts":{"id":8552,"post_id":22984,"comments":0,"score":2,"upvotes":2,"downvotes":0,"published":"2023-06-29T17:13:58.238286","newest_comment_time_necro":"2023-06-29T17:13:58.238286","newest_comment_time":"2023-06-29T17:13:58.238286","featured_community":false,"featured_local":false,"hot_rank":48,"hot_rank_active":48},"subscribed":"Subscribed","saved":false,"read":false,"creator_blocked":false,"my_vote":0,"unread_comments":0},"community_view":{"community":{"id":66,"name":"science","title":"Science","description":"Studies, research findings, and interesting tidbits from the ever-expanding scientific world.\n\nSubcommunities on Beehaw:\n\n- [Space](https://beehaw.org/c/space)\n\n----\n \nBe sure to also check out these other Fediverse science communities:\n\n- https://lemmy.ml/c/science\n- https://mander.xyz/c/science\n\n---\n\nThis community's icon was made by Aaron Schneider, under the [CC-BY-NC-SA 4.0 license](https://creativecommons.org/licenses/by-nc-sa/4.0/).","removed":false,"published":"2022-01-28T17:11:23.955280","updated":"2023-06-16T19:32:02.245431","deleted":false,"nsfw":false,"actor_id":"https://beehaw.org/c/science","local":false,"icon":"https://beehaw.org/pictrs/image/f83a7ff8-4e85-47a3-b4df-6a814e29c5d4.png","hidden":false,"posting_restricted_to_mods":false,"instance_id":16},"subscribed":"Subscribed","blocked":false,"counts":{"id":65,"community_id":66,"subscribers":1,"posts":282,"comments":843,"published":"2022-01-28T17:11:23.955280","users_active_day":42,"users_active_week":161,"users_active_month":493,"users_active_half_year":500,"hot_rank":0}},"moderators":[{"community":{"id":66,"name":"science","title":"Science","description":"Studies, research findings, and interesting tidbits from the ever-expanding scientific world.\n\nSubcommunities on Beehaw:\n\n- [Space](https://beehaw.org/c/space)\n\n----\n \nBe sure to also check out these other Fediverse science communities:\n\n- https://lemmy.ml/c/science\n- https://mander.xyz/c/science\n\n---\n\nThis community's icon was made by Aaron Schneider, under the [CC-BY-NC-SA 4.0 license](https://creati
06-30 08:00:51.807 13116 18031 I okhttp.OkHttpClient: vecommons.org/licenses/by-nc-sa/4.0/).","removed":false,"published":"2022-01-28T17:11:23.955280","updated":"2023-06-16T19:32:02.245431","deleted":false,"nsfw":false,"actor_id":"https://beehaw.org/c/science","local":false,"icon":"https://beehaw.org/pictrs/image/f83a7ff8-4e85-47a3-b4df-6a814e29c5d4.png","hidden":false,"posting_restricted_to_mods":false,"instance_id":16},"moderator":{"id":320,"name":"admin","display_name":"Chris Remington","avatar":"https://beehaw.org/pictrs/image/d29a8a53-296f-4e0f-a703-0593eb119d02.png","banned":false,"published":"2022-01-28T12:29:55.001133","updated":"2022-11-05T01:36:36.573721","actor_id":"https://beehaw.org/u/admin","bio":"@remington@masto.ai \n\nVolunteer amateur systems administrator for Beehaw. Stay-at-home dad. Outdoor enthusiast.","local":false,"banner":"https://beehaw.org/pictrs/image/63293086-8a81-474c-a5c3-32090099d3f0.jpeg","deleted":false,"matrix_user_id":"@removed:matrix.org","admin":false,"bot_account":false,"instance_id":16}},{"community":{"id":66,"name":"science","title":"Science","description":"Studies, research findings, and interesting tidbits from the ever-expanding scientific world.\n\nSubcommunities on Beehaw:\n\n- [Space](https://beehaw.org/c/space)\n\n----\n \nBe sure to also check out these other Fediverse science communities:\n\n- https://lemmy.ml/c/science\n- https://mander.xyz/c/science\n\n---\n\nThis community's icon was made by Aaron Schneider, under the [CC-BY-NC-SA 4.0 license](https://creativecommons.org/licenses/by-nc-sa/4.0/).","removed":false,"published":"2022-01-28T17:11:23.955280","updated":"2023-06-16T19:32:02.245431","deleted":false,"nsfw":false,"actor_id":"https://beehaw.org/c/science","local":false,"icon":"https://beehaw.org/pictrs/image/f83a7ff8-4e85-47a3-b4df-6a814e29c5d4.png","hidden":false,"posting_restricted_to_mods":false,"instance_id":16},"moderator":{"id":322,"name":"MicholasMouse","banned":false,"published":"2022-01-30T03:10:46.368046","updated":"2022-01-30T16:45:37.626019","actor_id":"https://beehaw.org/u/MicholasMouse","local":false,"deleted":false,"admin":false,"bot_account":false,"instance_id":16}},{"community":{"id":66,"name":"science","title":"Science","description":"Studies, research findings, and interesting tidbits from the ever-expanding scientific world.\n\nSubcommunities on Beehaw:\n\n- [Space](https://beehaw.org/c/space)\n\n----\n \nBe sure to also check out these other Fediverse science communities:\n\n- https://lemmy.ml/c/science\n- https://mander.xyz/c/science\n\n---\n\nThis community's icon was made by Aaron Schneider, under the [CC-BY-NC-SA 4.0 license](https://creativecommons.org/licenses/by-nc-sa/4.0/).","removed":false,"published":"2022-01-28T17:11:23.955280","updated":"2023-06-16T19:32:02.245431","deleted":false,"nsfw":false,"actor_id":"https://beehaw.org/c/science","local":false,"icon":"https://beehaw.org/pictrs/image/f83a7ff8-4e85-47a3-b4df-6a814e29c5d4.png","hidden":false,"posting_restricted_to_mods":false,"instance_id":16},"moderator":{"id":306,"name":"alyaza","display_name":"alyaza [they/she]","avatar":"https://beehaw.org/pictrs/image/018439e1-9b4d-4100-9ed1-78b4fa2cd68c.png","banned":false,"published":"2022-01-28T22:43:09.245896","updated":"2022-08-24T13:55:50.404458","actor_id":"https://beehaw.org/u/alyaza","bio":"internet gryphon. admin of Beehaw, mostly publicly interacting with people. nonbinary. they/she","local":false,"banner":"https://beehaw.org/pictrs/image/b508b38e-6171-4bd6-b736-ab68084c090b.png","deleted":false,"admin":false,"bot_account":false,"instance_id":16}},{"community":{"id":66,"name":"science","title":"Science","description":"Studies, research findings, and interesting tidbits from the ever-expanding scientific world.\n\nSubcommunities on Beehaw:\n\n- [Space](https://beehaw.org/c/space)\n\n----\n \nBe sure to also check out these other Fediverse science communities:\n\n- https://lemmy.ml/c/science\n- https://mander.xyz/c/science\n\n---\n\nThis community's icon was made by Aaron Schneider, under th
06-30 08:00:51.807 13116 18031 I okhttp.OkHttpClient: e [CC-BY-NC-SA 4.0 license](https://creativecommons.org/licenses/by-nc-sa/4.0/).","removed":false,"published":"2022-01-28T17:11:23.955280","updated":"2023-06-16T19:32:02.245431","deleted":false,"nsfw":false,"actor_id":"https://beehaw.org/c/science","local":false,"icon":"https://beehaw.org/pictrs/image/f83a7ff8-4e85-47a3-b4df-6a814e29c5d4.png","hidden":false,"posting_restricted_to_mods":false,"instance_id":16},"moderator":{"id":280,"name":"Gaywallet","avatar":"https://beehaw.org/pictrs/image/e11b4d06-f4e4-494e-8349-d006f8b3e956.png","banned":false,"published":"2022-01-28T23:01:12.455863","updated":"2022-12-30T22:29:42.647211","actor_id":"https://beehaw.org/u/Gaywallet","bio":"I'm gay","local":false,"deleted":false,"matrix_user_id":"@gaywallet:matrix.org","admin":false,"bot_account":false,"instance_id":16}},{"community":{"id":66,"name":"science","title":"Science","description":"Studies, research findings, and interesting tidbits from the ever-expanding scientific world.\n\nSubcommunities on Beehaw:\n\n- [Space](https://beehaw.org/c/space)\n\n----\n \nBe sure to also check out these other Fediverse science communities:\n\n- https://lemmy.ml/c/science\n- https://mander.xyz/c/science\n\n---\n\nThis community's icon was made by Aaron Schneider, under the [CC-BY-NC-SA 4.0 license](https://creativecommons.org/licenses/by-nc-sa/4.0/).","removed":false,"published":"2022-01-28T17:11:23.955280","updated":"2023-06-16T19:32:02.245431","deleted":false,"nsfw":false,"actor_id":"https://beehaw.org/c/science","local":false,"icon":"https://beehaw.org/pictrs/image/f83a7ff8-4e85-47a3-b4df-6a814e29c5d4.png","hidden":false,"posting_restricted_to_mods":false,"instance_id":16},"moderator":{"id":1135,"name":"realChem","avatar":"https://beehaw.org/pictrs/image/eb0aadf6-7a75-4054-b0e8-826fe50de173.png","banned":false,"published":"2023-06-07T13:02:20.088378","actor_id":"https://beehaw.org/u/realChem","bio":"he/him\n\nMaterials Science PhD candidate in Pittsburgh, PA, USA\n\nMy profile picture is the cover art from [*Not A Lot of Reasons to Sing, But Enough*](https://buttonpoetry.com/product/not-a-lot-of-reasons-to-sing-but-enough/), and was drawn by Casper Pham (recolor by me).","local":false,"banner":"https://beehaw.org/pictrs/image/ccb951ef-b5db-4d03-b6af-ca0e833845f5.jpeg","deleted":false,"admin":false,"bot_account":false,"instance_id":16}}],"cross_posts":[]}
06-30 08:00:51.807 13116 18031 I okhttp.OkHttpClient: <-- END HTTP (10376-byte body)
06-30 08:00:51.812 13116 18031 I okhttp.OkHttpClient: --> GET https://lemmy.example.com/api/v3/comment/list?auth=[AUTH_TOKEN]&max_depth=6&post_id=22984&sort=Hot&type_=All
06-30 08:00:51.812 13116 18031 I okhttp.OkHttpClient: User-Agent: Jerboa
06-30 08:00:51.812 13116 18031 I okhttp.OkHttpClient: --> END GET
06-30 08:00:51.826 13116 13116 D jerboa  : got to post activity
06-30 08:00:51.900 13116 13116 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10162; state: ENABLED
06-30 08:00:51.948 13116 18031 I okhttp.OkHttpClient: <-- 200 https://lemmy.example.com/api/v3/comment/list?auth=[AUTH_TOKEN]&max_depth=6&post_id=22984&sort=Hot&type_=All (135ms)
06-30 08:00:51.948 13116 18031 I okhttp.OkHttpClient: content-type: application/json
06-30 08:00:51.948 13116 18031 I okhttp.OkHttpClient: date: Fri, 30 Jun 2023 07:00:51 GMT
06-30 08:00:51.948 13116 18031 I okhttp.OkHttpClient: permissions-policy: interest-cohort=()
06-30 08:00:51.948 13116 18031 I okhttp.OkHttpClient: strict-transport-security: max-age=31536000
06-30 08:00:51.948 13116 18031 I okhttp.OkHttpClient: vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
06-30 08:00:51.948 13116 18031 I okhttp.OkHttpClient: x-content-type-options: nosniff
06-30 08:00:51.948 13116 18031 I okhttp.OkHttpClient: x-download-options: noopen
06-30 08:00:51.948 13116 18031 I okhttp.OkHttpClient: x-permitted-cross-domain-policies: none
06-30 08:00:51.948 13116 18031 I okhttp.OkHttpClient: x-robots-tag: none
06-30 08:00:51.948 13116 18031 I okhttp.OkHttpClient: x-xss-protection: 1; mode=block
06-30 08:00:51.948 13116 18031 I okhttp.OkHttpClient: content-length: 15
06-30 08:00:51.950 13116 18031 I okhttp.OkHttpClient: {"comments":[]}
06-30 08:00:51.950 13116 18031 I okhttp.OkHttpClient: <-- END HTTP (15-byte body)
06-30 08:00:51.956 13116 18035 D TrafficStats: tagSocket(112) with statsTag=0xffffffff, statsUid=-1
06-30 08:00:53.874 13116 13116 D jerboa  : got to post activity
--------- beginning of crash
06-30 08:00:53.879 13116 13116 E AndroidRuntime: FATAL EXCEPTION: main
06-30 08:00:53.879 13116 13116 E AndroidRuntime: Process: com.jerboa, PID: 13116
06-30 08:00:53.879 13116 13116 E AndroidRuntime: java.lang.IllegalStateException: You cannot access the NavBackStackEntry's ViewModels after the NavBackStackEntry is destroyed.
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.navigation.NavBackStackEntry.getViewModelStore(Unknown Source:69)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at coil.util.-Logs.viewModel(Unknown Source:14)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at okio.Utf8.PostActivity(Unknown Source:99)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at com.jerboa.MainActivity$onCreate$1$3$6$25$1.invoke(SourceFile:52)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at com.jerboa.MainActivity$onCreate$1$3$6$25$1.invoke(SourceFile:7)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at com.jerboa.ui.components.post.PostListingsKt$PostListings$1$1.invoke(Unknown Source:100)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:3)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:14)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.material.SwipeToDismissKt$SwipeToDismiss$2.invoke(Unknown Source:772)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:3)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.foundation.CanvasKt$Canvas$1.invoke(SourceFile:203)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.foundation.CanvasKt$Canvas$1.invoke(SourceFile:13)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Unknown Source:283)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at okhttp3.CertificatePinner$check$1.invoke(Unknown Source:573)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at okhttp3.CertificatePinner$check$1.invoke$1(Unknown Source:59)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at coil.util.-Logs.observeDerivedStateRecalculations(Unknown Source:42)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.doCompose(Unknown Source:128)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Unknown Source:35)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.recompose(Unknown Source:17)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.runtime.Recomposer.access$performRecompose(Unknown Source:100)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.material3.CheckboxKt$CheckboxImpl$1$1.invoke(Unknown Source:804)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(Unknown Source:6)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(Unknown Source:47)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:827)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
06-30 08:00:53.879 13116 13116 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@22fe79, androidx.compose.ui.platform.MotionDurationScaleImpl@30567be, StandaloneCoroutine{Cancelling}@9dd401f, AndroidUiDispatcher@3b7ef6c]
06-30 08:00:53.907 13116 13116 I Process : Sending signal. PID: 13116 SIG: 9
```
</details>

**Comment by Wiener234** [comment]
When going back from a post by swiping from left to right the app doesn't crash.

**Comment by scottwallacesh** [comment]
It _does_ crash for me when I use the OS gestures for swiping "Back".

-- 
Scott.

**Comment by scottwallacesh** [comment]
It _does_ crash for me when I use the OS gestures for swiping "Back".

**Comment by Wiener234** [comment]
I don't mean the OS gesture but the app gesture. You don't have to go from the left part of the screen. You could also start from the middle and swipe.

**Comment by vahtos** [comment]
It only seems to happen when pressing the back button on a post. It does not happen when viewing the image in a post and pressing the back button.

@Wiener234 thanks for the workaround, that does indeed work.

**Comment by MV-GH** [comment]
I have tried many things, but i cant get it to reproduce this. Can you clarify some more things, are you logged in, what postview mode you have, what user settings do you have or anything that helps

**Comment by vahtos** [comment]
Not the original reporter, but I am logged in, using the card view. Changing that doesn't seem to make a difference though.

I have also tried:

- Viewing All/Subscribed/Local
- Changing the sorting method (active, hot, new, etc.)
- Inverting all of my user settings
- Changing each setting in "Look and feel" one at time
- Inverting all of the "Look and feel" checkbox selections

Another note is it happens regardless of if you are looking at a specific community or the "Home" view.

Anything else you want me to try?

**Comment by MV-GH** [comment]
The back button, is it the button in the top left or the back button of android? Or does it happen with both?

**Comment by MV-GH** [comment]
Could you make a small recording

**Comment by vahtos** [comment]
It happens with both buttons.

I am on a Galaxy S10+, Android 12.

**Comment by vahtos** [comment]
https://github.com/dessalines/jerboa/assets/30844190/ee10bfec-d928-4d38-a450-1189b21d12ae

**Comment by MV-GH** [comment]
@nahwneeth Could you take a look at this?

**Comment by MV-GH** [comment]
@vahtos since i cant reproduce this, can you test if you can still reproduce in this build
[app-release.zip](https://github.com/dessalines/jerboa/files/11919857/app-release.zip)

I have removed the builtin swipe on post to return to the feed

**Comment by MV-GH** [comment]
One thing also, did this start with 0.37. as in it worked perfectly fine in 0.36?

**Comment by vahtos** [comment]
Yes, it was working fine in 0.36. I updated to 0.37 and immediately noticed this behavior (I also had the behavior in #928, but cleared cache and was fine).

I tried the version you linked, it does not have this bug (I logged in and set my settings and everything to make sure it was as close to a 1:1 test as possible).

**Comment by MV-GH** [comment]
Alright, thank you for your help. #817 This change must have introduced unintendended behaviour with the existing swipe to go to back functionality. I will revert  the swipe to feature for now until we have a definite way to reproduce and fix this problem.
The linked build is 0.37 build without this feature. For the other users experiencing this issue you can use that build for now

**Comment by MV-GH** [comment]
I made a small tweak to swipe to feature, could you test if the problem still occurs?
[app-release.zip](https://github.com/dessalines/jerboa/files/11923121/app-release.zip)

**Comment by vahtos** [comment]
Same behavior with that tweaked version.

**Comment by MV-GH** [comment]
So it still crashes

**Comment by vahtos** [comment]
Yes, it still crashes.

**Comment by nahwneeth** [comment]
https://github.com/google/accompanist/issues/1487

This seems to be a problem with the screen transitions. I'm not near a PC rn, @MV-GH can u remove dependency on accompanist-navigation and provide the apk, so people can confirm if it's not crashing. I'm not able to reproduce this issue on my end.

**Comment by MV-GH** [comment]
Wow your googlefu is much better than mine, from that thread i can gather it is because animationDurationScale is disabled. When i disable this I can 100% consistently reproduce this bug. That's already huge. @vahtos can you confirm that you have that disabled?

**Comment by vahtos** [comment]
Wow, yes. I have all animations disabled in the android developer settings.

**Comment by MV-GH** [comment]
Alright, i made a build with the new beta version of compose that supposedly fixes some of these issues. I can no longer reproduce this issue with this build. Can you confirm this is fixed with this build?
[app-release.zip](https://github.com/dessalines/jerboa/files/11924183/app-release.zip)

**Comment by vahtos** [comment]
Yes! That fixes it.
