### ISSUE TITLE
v0.0.37 crash on startup

### ISSUE THREAD

**Issue by Snellingen** [dessalines/jerboa#928]
**Jerboa Version**
0.0.37

**Android version + phone**
 Andoird 13 + Pixel 6 Pro

**Describe the bug**
The app instantly crash on startup and closes. The crash is caused by a java.lang.NullPointerException from the com.jerboa.ui.components.home.SiteViewModel > getSite function. 

**To Reproduce**
1. Open the app
2. It will crash, and if done enough times you can create an incident report to see the error. 

**Log:**

```
--------- beginning of crash
06-30 10:26:41.987 13533 13533 E AndroidRuntime: FATAL EXCEPTION: main
06-30 10:26:41.987 13533 13533 E AndroidRuntime: Process: com.jerboa, PID: 13533
06-30 10:26:41.987 13533 13533 E AndroidRuntime: java.lang.NullPointerException: Parameter specified as non-null is null: method com.jerboa.ui.components.home.SiteViewModel$getSite$1.invokeSuspend, parameter sortType
06-30 10:26:41.987 13533 13533 E AndroidRuntime:        at com.jerboa.ui.components.home.SiteViewModel$getSite$1.invokeSuspend(Unknown Source:111)
06-30 10:26:41.987 13533 13533 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
06-30 10:26:41.987 13533 13533 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
06-30 10:26:41.987 13533 13533 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
06-30 10:26:41.987 13533 13533 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
06-30 10:26:41.987 13533 13533 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
06-30 10:26:41.987 13533 13533 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
06-30 10:26:41.987 13533 13533 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7918)
06-30 10:26:41.987 13533 13533 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-30 10:26:41.987 13533 13533 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-30 10:26:41.987 13533 13533 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
06-30 10:26:41.987 13533 13533 E AndroidRuntime:        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f2710f3, Dispatchers.Main.immediate]
```

**Comment by Snellingen** [comment]
Clearing storage and cache removes the crash at startup. It now displays a proper error that the server version is too low (1.17.14). 
Even if the crash is caused by an unsupported server, the app should not crash and close without a proper error message.

**Comment by reric88** [comment]
> Clearing storage and cache removes the crash at startup. It now displays a proper error that the server version is too low (1.17.14). Even if the crash is caused by an unsupported server, the app should not crash and close without a proper error message.

This worked for me. Kept crashing on launch without an error. After clearing data I could access it again

**Comment by MV-GH** [comment]
Closing this as no longer relevant
