### ISSUE TITLE
app randomly crashes, even when in background 

### ISSUE THREAD

**Issue by Sikeen** [dessalines/jerboa#934]
**Jerboa Version**
0.0.35

**Android version + phone**
android 12, galaxy S10

**Describe the bug**
jerboa randomly crashes when browsing, and even when only the window is open and not in focus

**To Reproduce**
1. open the app
2. either browse or go out of it again
3. after some time it will randomly crash 

**application logs**

<details><summary>Logs</summary>

```
<details><summary>LOGS</summary>
--------- beginning of main
07-01 12:26:10.735 25090 25090 E USNET   : USNET: appName: com.jerboa
07-01 12:26:10.736 25090 25090 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
07-01 12:26:10.739 25090 25090 D ActivityThread: setConscryptValidator
07-01 12:26:10.739 25090 25090 D ActivityThread: setConscryptValidator - put
--------- beginning of system
07-01 12:26:10.754 25090 25090 D ActivityThread: handleBindApplication()++ app=com.jerboa
07-01 12:26:10.755 25090 25090 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10663; state: ENABLED
07-01 12:26:10.774 25090 25090 V GraphicsEnvironment: ANGLE Developer option for 'com.jerboa' set to: 'default'
07-01 12:26:10.774 25090 25090 V GraphicsEnvironment: App is not on the allowlist for updatable production driver.
07-01 12:26:10.779 25090 25090 D LoadedApk: LoadedApk::makeApplication() appContext.mOpPackageName=com.jerboa appContext.mBasePackageName=com.jerboa
07-01 12:26:10.780 25090 25090 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-01 12:26:10.782 25090 25090 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-01 12:26:10.786 25090 25090 D ActivityThread: handleBindApplication() --
07-01 12:26:10.794 25090 25110 D OpenGLRenderer: RenderThread::requireGlContext()
07-01 12:26:10.805 25090 25110 D OpenGLRenderer: RenderThread::setGrContext()
07-01 12:26:10.823 25090 25120 I okhttp.OkHttpClient: --> GET https://lemmy.ml/api/v3/post/list?auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMzNTMxLCJpc3MiOiJsZW1teS5tbCIsImlhdCI6MTY4NTgxOTAyOX0.4AimR9_isrELHZyncjisrliFiY6d4gTjy7fmdBv2zJw&sort=Hot&type_=Local
07-01 12:26:10.823 25090 25120 I okhttp.OkHttpClient: User-Agent: Jerboa
07-01 12:26:10.823 25090 25120 I okhttp.OkHttpClient: --> END GET
07-01 12:26:10.825 25090 25121 I okhttp.OkHttpClient: --> GET https://lemmy.ml/api/v3/user/unread_count?auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMzNTMxLCJpc3MiOiJsZW1teS5tbCIsImlhdCI6MTY4NTgxOTAyOX0.4AimR9_isrELHZyncjisrliFiY6d4gTjy7fmdBv2zJw
07-01 12:26:10.825 25090 25121 I okhttp.OkHttpClient: User-Agent: Jerboa
07-01 12:26:10.825 25090 25121 I okhttp.OkHttpClient: --> END GET
07-01 12:26:10.826 25090 25126 I okhttp.OkHttpClient: --> GET https://lemmy.ml/api/v3/site?auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMzNTMxLCJpc3MiOiJsZW1teS5tbCIsImlhdCI6MTY4NTgxOTAyOX0.4AimR9_isrELHZyncjisrliFiY6d4gTjy7fmdBv2zJw
07-01 12:26:10.826 25090 25126 I okhttp.OkHttpClient: User-Agent: Jerboa
07-01 12:26:10.826 25090 25126 I okhttp.OkHttpClient: --> END GET
07-01 12:26:10.832 25090 25090 I DecorView: [INFO] isPopOver=false, config=true
07-01 12:26:10.832 25090 25090 I DecorView: updateCaptionType >> DecorView@e85809d[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
07-01 12:26:10.832 25090 25090 D DecorView: setCaptionType = 0, this = DecorView@e85809d[]
07-01 12:26:10.833 25090 25090 I DecorView: getCurrentDensityDpi: from real metrics. densityDpi=560 msg=resources_loaded
07-01 12:26:10.839 25090 25090 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
07-01 12:26:10.843 25090 25090 I ViewRootImpl@afd686a[MainActivity]: setView = com.android.internal.policy.DecorView@e85809d TM=true
07-01 12:26:10.866 25090 25090 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
07-01 12:26:10.872 25090 25090 I ViewRootImpl@afd686a[MainActivity]: Relayout returned: old=(0,0,1440,3040) new=(0,0,1440,3040) req=(1440,3040)0 dur=4 res=0x7 s={true 489756631968} ch=true fn=-1
07-01 12:26:10.873 25090 25090 I ViewRootImpl@afd686a[MainActivity]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11442 android.view.ViewRootImpl.performTraversals:4198 android.view.ViewRootImpl.doTraversal:2924 
07-01 12:26:10.873 25090 25090 D ViewRootImpl@afd686a[MainActivity]: Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
07-01 12:26:10.874 25090 25090 D ViewRootImpl@afd686a[MainActivity]: Creating frameCompleteCallback
07-01 12:26:10.875 25090 25110 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
07-01 12:26:10.876 25090 25110 D OpenGLRenderer: eglCreateWindowSurface
07-01 12:26:10.877 25090 25142 I Gralloc4: mapper 4.x is not supported
07-01 12:26:10.877 25090 25144 D ViewRootImpl@afd686a[MainActivity]: Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
07-01 12:26:10.877 25090 25142 W Gralloc3: mapper 3.x is not supported
07-01 12:26:10.878 25090 25142 I gralloc : Arm Module v1.0
07-01 12:26:10.879 25090 25142 W Gralloc4: allocator 4.x is not supported
07-01 12:26:10.879 25090 25142 W Gralloc3: allocator 3.x is not supported
07-01 12:26:10.886 25090 25110 D ViewRootImpl@afd686a[MainActivity]: Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
07-01 12:26:10.887 25090 25090 I ViewRootImpl@afd686a[MainActivity]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:5000 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
07-01 12:26:10.887 25090 25090 I ViewRootImpl@afd686a[MainActivity]: [DP] rdf()
07-01 12:26:10.887 25090 25090 D ViewRootImpl@afd686a[MainActivity]: reportDrawFinished (fn: -1) 
07-01 12:26:10.897 25090 25090 D jerboa  : got to home activity
07-01 12:26:10.901 25090 25090 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10663; state: ENABLED
07-01 12:26:10.929 25090 25090 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_NAVIGATION_BAR on com.jerboa/com.jerboa.MainActivity
07-01 12:26:10.929 25090 25090 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_STATUS_BAR on com.jerboa/com.jerboa.MainActivity
07-01 12:26:10.931 25090 25090 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
07-01 12:26:10.937 25090 25090 D jerboa  : got to home activity
07-01 12:26:10.941 25090 25090 I ViewRootImpl@afd686a[MainActivity]: Relayout returned: old=(0,0,1440,3040) new=(0,0,1440,3040) req=(1440,3040)0 dur=3 res=0x1 s={true 489756631968} ch=false fn=4
07-01 12:26:10.942 25090 25090 I ViewRootImpl@afd686a[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
07-01 12:26:10.943 25090 25090 D InputMethodManager: startInputInner - Id : 0
07-01 12:26:10.943 25090 25090 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
07-01 12:26:10.958 25090 25090 D InputMethodManager: startInputInner - Id : 0
07-01 12:26:11.461 25090 25090 I ViewRootImpl@afd686a[MainActivity]: ViewPostIme pointer 0
07-01 12:26:11.578 25090 25090 I ViewRootImpl@afd686a[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
07-01 12:26:12.232 25090 25090 I ViewRootImpl@afd686a[MainActivity]: handleAppVisibility mAppVisible=true visible=false
07-01 12:26:12.232 25090 25090 I ViewRootImpl@afd686a[MainActivity]: stopped(true) old=false
07-01 12:26:12.246 25090 25110 D OpenGLRenderer: setSurface called with nullptr
07-01 12:26:12.246 25090 25110 D OpenGLRenderer: setSurface() destroyed EGLSurface
07-01 12:26:12.246 25090 25110 D OpenGLRenderer: destroyEglSurface
07-01 12:26:12.251 25090 25090 I ViewRootImpl@afd686a[MainActivity]: Relayout returned: old=(0,0,1440,3040) new=(0,0,1440,3040) req=(1440,3040)8 dur=4 res=0x5 s={false 0} ch=false fn=-1
07-01 12:26:12.253 25090 25090 D InputTransport: Input channel destroyed: 'ClientS', fd=115
07-01 12:26:16.807 25090 25222 D ProfileInstaller: Skipping profile installation for com.jerboa
07-01 12:26:21.043 25090 25120 I okhttp.OkHttpClient: <-- HTTP FAILED: java.net.SocketTimeoutException: timeout
07-01 12:26:21.045 25090 25126 I okhttp.OkHttpClient: <-- HTTP FAILED: java.net.SocketTimeoutException: timeout
07-01 12:26:21.046 25090 25121 I okhttp.OkHttpClient: <-- HTTP FAILED: java.net.SocketTimeoutException: timeout
--------- beginning of crash
07-01 12:26:21.049 25090 25090 E AndroidRuntime: FATAL EXCEPTION: main
07-01 12:26:21.049 25090 25090 E AndroidRuntime: Process: com.jerboa, PID: 25090
07-01 12:26:21.049 25090 25090 E AndroidRuntime: java.net.SocketTimeoutException: timeout
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at a8.v.j(Unknown Source:4)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at a8.v.l(Unknown Source:8)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at a8.q.g(Unknown Source:58)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at x7.f.d(Unknown Source:2)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at y7.b.a(Unknown Source:267)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at y7.g.b(Unknown Source:138)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at x7.a.a(Unknown Source:127)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at y7.g.b(Unknown Source:138)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at v7.a.a(Unknown Source:125)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at y7.g.b(Unknown Source:138)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at y7.a.a(Unknown Source:175)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at y7.g.b(Unknown Source:138)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at y7.h.a(Unknown Source:162)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at y7.g.b(Unknown Source:138)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at g8.b.a(Unknown Source:568)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at y7.g.b(Unknown Source:138)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at w4.a.a(Unknown Source:22)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at y7.g.b(Unknown Source:138)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at x7.n.h(Unknown Source:95)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at x7.k.run(Unknown Source:49)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:920)
07-01 12:26:21.049 25090 25090 E AndroidRuntime:        Suppressed: p7.f: [m1{Cancelling}@fca2300, Dispatchers.Main.immediate]
</details>
```

</details>

**Comment by MV-GH** [comment]
The logs are from a version before I disabled obfuscation. But from the error I can tell it is a general network failure. For example a vote. That would crash the application. This should be fixed in 0.36 already.
